"""
Verification script to check that all LangChain foundation modules have proper docstrings.

This script inspects all classes and methods in the LangChain foundation modules
to ensure they have comprehensive docstrings with parameter and return descriptions.
"""

import inspect
from typing import List, Tuple


def check_docstrings(module_path: str, module_name: str) -> Tuple[bool, List[str]]:
    """
    Check if all classes and methods in a module have docstrings.
    
    Args:
        module_path: Import path for the module
        module_name: Display name for the module
    
    Returns:
        Tuple of (success: bool, issues: List[str])
    """
    issues = []
    
    # Methods to skip (auto-generated by Pydantic or standard library)
    skip_methods = {
        'dict', 'json', 'copy', 'model_copy', 'model_dump', 
        'model_dump_json', 'model_post_init', '__init__'
    }
    
    try:
        # Import the module
        module = __import__(module_path, fromlist=[''])
        
        # Get all classes in the module
        classes = [obj for name, obj in inspect.getmembers(module, inspect.isclass)
                   if obj.__module__ == module_path]
        
        for cls in classes:
            # Check class docstring
            if not cls.__doc__ or len(cls.__doc__.strip()) < 20:
                issues.append(f"  ❌ Class {cls.__name__} missing or insufficient docstring")
            else:
                print(f"  ✓ Class {cls.__name__} has docstring")
            
            # Check method docstrings (excluding auto-generated ones)
            methods = [name for name, obj in inspect.getmembers(cls, inspect.isfunction)
                      if not name.startswith('_') and name not in skip_methods]
            
            for method_name in methods:
                method = getattr(cls, method_name)
                if not method.__doc__ or len(method.__doc__.strip()) < 20:
                    issues.append(f"  ❌ Method {cls.__name__}.{method_name} missing or insufficient docstring")
                else:
                    print(f"  ✓ Method {cls.__name__}.{method_name} has docstring")
        
        # Check module-level functions
        functions = [obj for name, obj in inspect.getmembers(module, inspect.isfunction)
                    if obj.__module__ == module_path and not name.startswith('_')]
        
        for func in functions:
            if not func.__doc__ or len(func.__doc__.strip()) < 20:
                issues.append(f"  ❌ Function {func.__name__} missing or insufficient docstring")
            else:
                print(f"  ✓ Function {func.__name__} has docstring")
        
    except Exception as e:
        issues.append(f"  ❌ Error checking module: {e}")
    
    return len(issues) == 0, issues


def main():
    """Run docstring verification for all LangChain foundation modules."""
    print("=" * 70)
    print("LangChain Foundation Docstring Verification")
    print("=" * 70)
    
    modules_to_check = [
        ("app.agents.context", "Agent Context Models"),
        ("app.agents.base", "Base Agent Class"),
        ("app.agents.test_agent", "Test Agent Implementation"),
        ("app.services.context_loader", "Context Loader Service"),
        ("app.services.agent_orchestrator", "Agent Orchestrator"),
        ("app.core.config", "Configuration"),
    ]
    
    all_success = True
    all_issues = []
    
    for module_path, module_name in modules_to_check:
        print(f"\n{module_name} ({module_path}):")
        print("-" * 70)
        
        success, issues = check_docstrings(module_path, module_name)
        
        if not success:
            all_success = False
            all_issues.extend(issues)
            for issue in issues:
                print(issue)
        else:
            print(f"  ✓ All docstrings present and sufficient")
    
    print("\n" + "=" * 70)
    if all_success:
        print("✅ SUCCESS: All modules have proper docstrings!")
    else:
        print("❌ ISSUES FOUND:")
        for issue in all_issues:
            print(issue)
        print(f"\nTotal issues: {len(all_issues)}")
    print("=" * 70)
    
    return 0 if all_success else 1


if __name__ == "__main__":
    exit(main())
