"""
Meal Plan Generator Service

Generates personalized meal plans based on user fitness level, goals, workout plan,
and dietary preferences. Uses LLM with structured output to dynamically generate
varied, real meal suggestions tailored to each user's requirements.
"""
from pydantic import BaseModel, Field, field_validator
from typing import List, Literal, Optional
from enum import Enum
import logging

logger = logging.getLogger(__name__)


class MealType(str, Enum):
    """Types of meals."""
    BREAKFAST = "breakfast"
    LUNCH = "lunch"
    DINNER = "dinner"
    SNACK = "snack"
    PRE_WORKOUT = "pre_workout"
    POST_WORKOUT = "post_workout"


class SampleMeal(BaseModel):
    """Sample meal idea."""
    meal_type: MealType
    name: str
    name_hindi: Optional[str] = Field(default=None, description="Hindi name of the dish if applicable")
    ingredients: List[str]
    approximate_calories: int
    approximate_protein_g: int
    approximate_carbs_g: int
    approximate_fats_g: int
    prep_time_minutes: int


# ------------------------------------------------------------------
# Structured Output Schemas for LLM
# ------------------------------------------------------------------

class GeneratedMeal(BaseModel):
    """A single meal generated by the LLM."""
    meal_type: str = Field(description="One of: breakfast, lunch, dinner, snack, pre_workout, post_workout")
    name: str = Field(description="Specific, real dish name (e.g., 'Chicken Tikka with Brown Rice')")
    name_hindi: Optional[str] = Field(default=None, description="Hindi name if the dish is Indian")
    ingredients: List[str] = Field(description="List of main ingredients with approximate quantities")
    approximate_calories: int = Field(description="Realistic calorie count for this dish")
    approximate_protein_g: int = Field(description="Protein in grams")
    approximate_carbs_g: int = Field(description="Carbohydrates in grams")
    approximate_fats_g: int = Field(description="Fats in grams")
    prep_time_minutes: int = Field(description="Total prep + cook time in minutes")


class GeneratedMealSet(BaseModel):
    """Complete set of meals generated by the LLM for a weekly plan."""
    meals: List[GeneratedMeal] = Field(
        description="List of unique meal options. Generate 7 meals per requested meal type."
    )


class MealPlan(BaseModel):
    """Complete meal plan."""
    diet_type: str  # omnivore/vegetarian/vegan/pescatarian
    allergies: List[str]
    dislikes: List[str]
    meal_frequency: int = Field(ge=2, le=6, description="Meals per day")
    meal_prep_level: str  # low/medium/high
    daily_calories: int = Field(ge=1200, le=5000)
    protein_g: int
    carbs_g: int
    fats_g: int
    sample_meals: List[SampleMeal]
    meal_timing_suggestions: str
    
    @field_validator('diet_type', mode='before')
    @classmethod
    def validate_diet_type(cls, v: str) -> str:
        valid_types = ["omnivore", "vegetarian", "vegan", "pescatarian"]
        if not isinstance(v, str):
            return "omnivore"
        val = v.lower()
        if val == "non-veg" or val == "non-vegetarian":
            return "omnivore"
        if val not in valid_types:
            logger.warning(f"Invalid diet_type {v}, defaulting to omnivore")
            return "omnivore"
        return val
    
    @field_validator('meal_prep_level', mode='before')
    @classmethod
    def validate_meal_prep_level(cls, v: str) -> str:
        valid_levels = ["low", "medium", "high"]
        if not isinstance(v, str):
            return "medium"
        val = v.lower()
        if val not in valid_levels:
            logger.warning(f"Invalid meal_prep_level {v}, defaulting to medium")
            return "medium"
        return val



class MealPlanGenerator:
    """
    Service for generating personalized meal plans.
    
    Uses LLM structured output to dynamically generate varied, real meal
    suggestions based on user profile and preferences. Falls back to a
    static meal database if LLM is unavailable.
    """
    
    # Standard calorie multipliers for TDEE estimation based on workout frequency
    ACTIVITY_MULTIPLIERS = {
        2: 1.2,   # 2 days/week - lightly active
        3: 1.375, # 3 days/week - moderately active
        4: 1.55,  # 4 days/week - very active
        5: 1.725, # 5+ days/week - extremely active
        6: 1.725,
        7: 1.9
    }
    
    def __init__(self):
        """Initialize MealPlanGenerator."""
        self._llm = None
        self._structured_llm = None
    
    def _get_llm(self):
        """Lazy-initialize the LLM using the same provider config as agents."""
        if self._llm is not None:
            return self._llm
        
        from app.core.config import settings, LLMProvider
        
        api_key = settings.get_required_llm_api_key()
        
        if settings.LLM_PROVIDER == LLMProvider.ANTHROPIC:
            from langchain_anthropic import ChatAnthropic
            self._llm = ChatAnthropic(
                model=settings.LLM_MODEL,
                anthropic_api_key=api_key,
                temperature=0.7,
                max_tokens=4096
            )
        elif settings.LLM_PROVIDER == LLMProvider.OPENAI:
            from langchain_openai import ChatOpenAI
            self._llm = ChatOpenAI(
                model=settings.LLM_MODEL,
                openai_api_key=api_key,
                temperature=0.7,
                max_tokens=4096
            )
        elif settings.LLM_PROVIDER == LLMProvider.GOOGLE:
            from langchain_google_genai import ChatGoogleGenerativeAI
            self._llm = ChatGoogleGenerativeAI(
                model=settings.LLM_MODEL,
                google_api_key=api_key,
                temperature=0.7,
                max_output_tokens=4096
            )
        else:
            raise ValueError(f"Unsupported LLM provider: {settings.LLM_PROVIDER}")
        
        return self._llm
    
    def _get_structured_llm(self):
        """Get an LLM instance bound to GeneratedMealSet structured output."""
        if self._structured_llm is not None:
            return self._structured_llm
        
        llm = self._get_llm()
        self._structured_llm = llm.with_structured_output(GeneratedMealSet)
        return self._structured_llm
    
    async def generate_plan(
        self,
        fitness_level: str,
        primary_goal: str,
        workout_plan: dict,
        diet_type: str,
        allergies: List[str],
        dislikes: List[str],
        meal_frequency: int,
        meal_prep_level: str,
        weight_kg: float = 75.0,
        height_cm: float = 175.0,
        age: int = 30,
        gender: str = "male"
    ) -> MealPlan:
        """
        Generate a meal plan based on user profile and preferences.
        
        Uses LLM structured output to create varied, realistic meal
        suggestions tailored to the user's exact requirements.
        """
        logger.info(f"Generating meal plan for {primary_goal} goal with {diet_type} diet")
        
        # Validate inputs
        self._validate_inputs(diet_type, meal_frequency, meal_prep_level)
        
        # Calculate calorie target based on goal and workout plan
        workout_frequency = workout_plan.get("frequency", 3)
        daily_calories = self._calculate_calorie_target(
            primary_goal, workout_frequency, weight_kg, height_cm, age, gender
        )
        
        # Calculate macro breakdown
        protein_g, carbs_g, fats_g = self._calculate_macros(
            daily_calories=daily_calories,
            primary_goal=primary_goal,
            workout_frequency=workout_frequency,
            weight_kg=weight_kg
        )
        
        # Determine which meal types to generate based on frequency
        meal_types_needed = self._determine_meal_types(meal_frequency)
        
        # Generate meals dynamically via LLM structured output
        sample_meals = await self._generate_meals_via_llm(
            diet_type=diet_type,
            allergies=allergies,
            dislikes=dislikes,
            meal_types_needed=meal_types_needed,
            meal_prep_level=meal_prep_level,
            daily_calories=daily_calories,
            protein_g=protein_g,
            carbs_g=carbs_g,
            fats_g=fats_g,
            primary_goal=primary_goal,
            meal_frequency=meal_frequency
        )
        
        # Generate meal timing suggestions
        meal_timing = self._generate_meal_timing(meal_frequency, workout_frequency)
        
        return MealPlan(
            diet_type=diet_type,
            allergies=allergies,
            dislikes=dislikes,
            meal_frequency=meal_frequency,
            meal_prep_level=meal_prep_level,
            daily_calories=daily_calories,
            protein_g=protein_g,
            carbs_g=carbs_g,
            fats_g=fats_g,
            sample_meals=sample_meals,
            meal_timing_suggestions=meal_timing
        )

    
    async def modify_plan(
        self,
        current_plan: dict,
        modifications: dict
    ) -> MealPlan:
        """
        Modify an existing meal plan based on user feedback.
        
        Args:
            current_plan: Current MealPlan as dict
            modifications: Dict with requested changes
                
        Returns:
            Modified MealPlan object
        """
        logger.info(f"Modifying meal plan with changes: {modifications}")
        
        if isinstance(current_plan, MealPlan):
            plan = current_plan
        else:
            plan = MealPlan(**current_plan)
        
        needs_meal_regen = False
        
        if "daily_calories" in modifications:
            new_calories = modifications["daily_calories"]
            if not (1200 <= new_calories <= 5000):
                raise ValueError("daily_calories must be between 1200 and 5000")
            
            old_calories = (plan.protein_g * 4) + (plan.carbs_g * 4) + (plan.fats_g * 9)
            if old_calories > 0:
                ratio = new_calories / old_calories
                plan.protein_g = int(plan.protein_g * ratio)
                plan.carbs_g = int(plan.carbs_g * ratio)
                plan.fats_g = int(plan.fats_g * ratio)
            
            plan.daily_calories = new_calories
            needs_meal_regen = True
        
        if "protein_g" in modifications:
            new_protein = modifications["protein_g"]
            if new_protein < 0:
                raise ValueError("protein_g must be positive")
            
            protein_calories = new_protein * 4
            old_protein_calories = plan.protein_g * 4
            calorie_diff = protein_calories - old_protein_calories
            
            carb_adjustment = int((calorie_diff * 0.6) / 4)
            fat_adjustment = int((calorie_diff * 0.4) / 9)
            
            plan.protein_g = new_protein
            plan.carbs_g = max(0, plan.carbs_g - carb_adjustment)
            plan.fats_g = max(0, plan.fats_g - fat_adjustment)
        
        if "meal_frequency" in modifications:
            new_frequency = modifications["meal_frequency"]
            if not (2 <= new_frequency <= 6):
                raise ValueError("meal_frequency must be between 2 and 6")
            
            plan.meal_frequency = new_frequency
            plan.meal_timing_suggestions = self._generate_meal_timing(plan.meal_frequency, 3)
            needs_meal_regen = True
        
        if needs_meal_regen:
            meal_types_needed = self._determine_meal_types(plan.meal_frequency)
            plan.sample_meals = await self._generate_meals_via_llm(
                diet_type=plan.diet_type,
                allergies=plan.allergies,
                dislikes=plan.dislikes,
                meal_types_needed=meal_types_needed,
                meal_prep_level=plan.meal_prep_level,
                daily_calories=plan.daily_calories,
                protein_g=plan.protein_g,
                carbs_g=plan.carbs_g,
                fats_g=plan.fats_g,
                primary_goal="general_fitness",
                meal_frequency=plan.meal_frequency
            )
        
        return plan

    
    def _validate_inputs(self, diet_type: str, meal_frequency: int, meal_prep_level: str) -> None:
        """Validate input parameters."""
        valid_diet_types = ["omnivore", "vegetarian", "vegan", "pescatarian"]
        if diet_type not in valid_diet_types:
            raise ValueError(f"diet_type must be one of {valid_diet_types}")
        if not (2 <= meal_frequency <= 6):
            raise ValueError("meal_frequency must be between 2 and 6")
        valid_prep_levels = ["low", "medium", "high"]
        if meal_prep_level not in valid_prep_levels:
            raise ValueError(f"meal_prep_level must be one of {valid_prep_levels}")
    
    def _calculate_calorie_target(
        self, primary_goal: str, workout_frequency: int, 
        weight_kg: float, height_cm: float, age: int, gender: str
    ) -> int:
        """Calculate daily calorie target based on Mifflin-St Jeor equation and goal."""
        if gender.lower().strip() == "female":
            bmr = (10 * weight_kg) + (6.25 * height_cm) - (5 * age) - 161
        else:
            bmr = (10 * weight_kg) + (6.25 * height_cm) - (5 * age) + 5
            
        activity_multiplier = self.ACTIVITY_MULTIPLIERS.get(workout_frequency, 1.375)
        tdee = int(bmr * activity_multiplier)
        
        if primary_goal == "muscle_gain":
            return tdee + 400
        elif primary_goal == "fat_loss":
            return tdee - 400
        else:
            return tdee
    
    def _calculate_macros(
        self, daily_calories: int, primary_goal: str,
        workout_frequency: int, weight_kg: float
    ) -> tuple[int, int, int]:
        """Calculate protein, carbs, and fats in grams."""
        if primary_goal == "muscle_gain":
            protein_g = int(weight_kg * 2.0)
        elif primary_goal == "fat_loss":
            protein_g = int(weight_kg * 1.8)
        else:
            protein_g = int(weight_kg * 1.6)
        
        protein_calories = protein_g * 4
        remaining_calories = daily_calories - protein_calories
        
        fat_percentage = 0.28
        fat_calories = int(remaining_calories * fat_percentage)
        fats_g = int(fat_calories / 9)
        
        carb_calories = remaining_calories - fat_calories
        carbs_g = int(carb_calories / 4)
        
        calculated_calories = (protein_g * 4) + (carbs_g * 4) + (fats_g * 9)
        tolerance = daily_calories * 0.1
        
        if abs(calculated_calories - daily_calories) > tolerance:
            logger.warning(f"Macro sum {calculated_calories} differs from target {daily_calories}")
            carb_adjustment = (daily_calories - calculated_calories) / 4
            carbs_g = int(carbs_g + carb_adjustment)
        
        return protein_g, carbs_g, fats_g
    
    def _determine_meal_types(self, meal_frequency: int) -> List[str]:
        """Determine which meal types to generate based on frequency."""
        if meal_frequency == 2:
            return ["breakfast", "dinner"]
        elif meal_frequency == 3:
            return ["breakfast", "lunch", "dinner"]
        elif meal_frequency == 4:
            return ["breakfast", "lunch", "snack", "dinner"]
        elif meal_frequency == 5:
            return ["breakfast", "snack", "lunch", "pre_workout", "dinner"]
        else:  # 6
            return ["breakfast", "snack", "lunch", "pre_workout", "dinner", "post_workout"]

    async def _generate_meals_via_llm(
        self,
        diet_type: str,
        allergies: List[str],
        dislikes: List[str],
        meal_types_needed: List[str],
        meal_prep_level: str,
        daily_calories: int,
        protein_g: int,
        carbs_g: int,
        fats_g: int,
        primary_goal: str,
        meal_frequency: int
    ) -> List[SampleMeal]:
        """
        Generate meals using LLM with structured output.
        
        Uses with_structured_output() to guarantee the LLM returns a
        schema-compliant GeneratedMealSet Pydantic object. Falls back
        to static meals if the LLM call fails.
        """
        meal_types_str = ", ".join(meal_types_needed)
        cals_per_meal = daily_calories // meal_frequency
        protein_per_meal = protein_g // meal_frequency
        carbs_per_meal = carbs_g // meal_frequency
        fats_per_meal = fats_g // meal_frequency
        
        allergy_str = ", ".join(allergies) if allergies else "none"
        dislike_str = ", ".join(dislikes) if dislikes else "none"
        
        prep_guidance = {
            "low": "Quick and easy, under 15 minutes prep. Ready-to-eat or minimal cooking.",
            "medium": "Moderate prep, 15-30 minutes. Standard home cooking.",
            "high": "Can be complex, 30-60 minutes. Elaborate recipes are fine."
        }.get(meal_prep_level, "Moderate prep, 15-30 minutes.")
        
        prompt = f"""You are an expert nutritionist creating a 7-day meal plan. Generate exactly 7 unique, real meal options for EACH of these meal types: {meal_types_str}.

User profile:
- Diet: {diet_type}
- Goal: {primary_goal.replace('_', ' ')}
- Allergies: {allergy_str}
- Dislikes: {dislike_str}
- Prep level: {prep_guidance}

Target macros per main meal (breakfast, lunch, dinner):
- Calories: ~{cals_per_meal} kcal | Protein: ~{protein_per_meal}g | Carbs: ~{carbs_per_meal}g | Fat: ~{fats_per_meal}g

For snack/pre_workout/post_workout, use HALF the above targets.

IMPORTANT RULES:
1. Every meal must be a REAL, specific dish — not generic names like "healthy lunch"
2. Include a diverse mix of cuisines — Indian, Mediterranean, Asian, Western, Mexican, etc.
3. Provide realistic calorie and macro values that approximate the targets (±20% is OK)
4. STRICTLY avoid all listed allergens and dislikes in ingredients
5. Vary primary protein and carb sources across the 7 options — no two meals of the same type should use the same main ingredient
6. If diet is vegetarian, NO meat/fish. If vegan, NO animal products at all.
7. If a dish has a common Hindi name, include it in name_hindi field
8. Include approximate quantities in ingredients (e.g., "200g chicken breast", "1 cup rice")

Generate {7 * len(meal_types_needed)} total meals ({len(meal_types_needed)} types × 7 each)."""

        try:
            structured_llm = self._get_structured_llm()
            logger.info(f"Generating {len(meal_types_needed)} meal types via LLM structured output...")
            
            result: GeneratedMealSet = await structured_llm.ainvoke(prompt)
            
            if not result or not result.meals:
                raise RuntimeError(
                    "LLM returned empty response for meal generation. "
                    "Please check your LLM API key and try again."
                )
            
            # Convert GeneratedMeal → SampleMeal with validation
            sample_meals = []
            for gm in result.meals:
                try:
                    meal_type_raw = gm.meal_type.lower().strip()
                    try:
                        meal_type = MealType(meal_type_raw)
                    except ValueError:
                        logger.warning(f"Invalid meal_type '{meal_type_raw}' from LLM, skipping")
                        continue
                    
                    sample_meals.append(SampleMeal(
                        meal_type=meal_type,
                        name=gm.name,
                        name_hindi=gm.name_hindi,
                        ingredients=gm.ingredients,
                        approximate_calories=max(50, gm.approximate_calories),
                        approximate_protein_g=max(0, gm.approximate_protein_g),
                        approximate_carbs_g=max(0, gm.approximate_carbs_g),
                        approximate_fats_g=max(0, gm.approximate_fats_g),
                        prep_time_minutes=max(1, min(180, gm.prep_time_minutes))
                    ))
                except Exception as e:
                    logger.warning(f"Skipping malformed LLM meal: {e}")
                    continue
            
            if len(sample_meals) < 3:
                raise RuntimeError(
                    f"LLM generated only {len(sample_meals)} valid meals, expected at least {len(meal_types_needed) * 7}. "
                    "Please try again."
                )
            
            type_counts = {}
            for m in sample_meals:
                type_counts[m.meal_type.value] = type_counts.get(m.meal_type.value, 0) + 1
            logger.info(f"LLM generated {len(sample_meals)} meals: {type_counts}")
            
            return sample_meals
            
        except Exception as e:
            logger.error(f"LLM meal generation failed: {e}", exc_info=True)
            raise RuntimeError(f"Failed to generate meal plan: {e}") from e
    
    def _generate_meal_timing(self, meal_frequency: int, workout_frequency: int) -> str:
        """Generate meal timing suggestions."""
        if meal_frequency == 2:
            return "Breakfast (8-9am), Dinner (6-7pm). Have a carb-rich meal 2-3 hours before workouts."
        elif meal_frequency == 3:
            return "Breakfast (7-8am), Lunch (12-1pm), Dinner (6-7pm). Have a carb-rich meal 2-3 hours before workouts."
        elif meal_frequency == 4:
            return "Breakfast (7-8am), Lunch (12-1pm), Snack (3-4pm), Dinner (7-8pm). Time snack around workouts for energy."
        elif meal_frequency == 5:
            return "Breakfast (7am), Snack (10am), Lunch (1pm), Snack (4pm), Dinner (7pm). Pre-workout snack 1-2 hours before training."
        else:  # 6 meals
            return "Breakfast (7am), Snack (9:30am), Lunch (12pm), Snack (3pm), Dinner (6pm), Evening Snack (8:30pm). Distribute protein evenly."

