/**
 * Onboarding Type Definitions
 * 
 * These types define the structure of onboarding-related requests and responses
 * for the Shuren API. They align with the backend FastAPI endpoints.
 */

/**
 * Agent types for onboarding flow
 * Maps to backend OnboardingAgentType enum
 */
export const AgentType = {
  FITNESS_ASSESSMENT: 'fitness_assessment',
  GOAL_SETTING: 'goal_setting',
  WORKOUT_PLANNING: 'workout_planning',
  DIET_PLANNING: 'diet_planning',
  SCHEDULING: 'scheduling'
} as const;

export type AgentType = typeof AgentType[keyof typeof AgentType];

/**
 * Onboarding progress response
 * Returned by GET /api/v1/onboarding/progress
 * Contains current state, completion status, and metadata
 */
export interface OnboardingProgress {
  current_state: number;
  total_states: number;
  completed_states: number[];
  is_complete: boolean;
  completion_percentage: number;
  can_complete: boolean;
  current_state_info: StateMetadata;
  next_state_info: StateMetadata | null;
}

/**
 * State metadata for UI rendering
 * Provides information about each onboarding state
 */
export interface StateMetadata {
  state_number: number;
  name: string;
  agent: AgentType;
  description: string;
  required_fields: string[];
}

/**
 * Onboarding chat request
 * Sent to POST /api/v1/chat/onboarding
 */
export interface OnboardingChatRequest {
  message: string;
  current_state: number;
}

/**
 * Onboarding chat response
 * Returned by POST /api/v1/chat/onboarding
 * Contains agent response and state update information
 */
export interface OnboardingChatResponse {
  response: string;
  agent_type: string;
  state_updated: boolean;
  new_state?: number;
  is_complete: boolean;
  progress: {
    current_state: number;
    completion_percentage: number;
  };
}

/**
 * Onboarding stream chunk
 * Streamed from GET /api/v1/chat/onboarding-stream (SSE)
 * Contains incremental response data and state updates
 */
export interface OnboardingStreamChunk {
  chunk?: string;
  done?: boolean;
  error?: string;
  agent_type?: string;
  state_updated?: boolean;
  new_state?: number;
  progress?: {
    current_state: number;
    total_states: number;
    completed_states: number[];
    completion_percentage: number;
    is_complete: boolean;
    can_complete: boolean;
  };
}

/**
 * Onboarding Workout Plan structure
 * Generated by workout planning agent during onboarding
 * This is a preview/proposal plan shown to user for approval
 */
export interface OnboardingWorkoutPlan {
  frequency: number;
  location: string;
  duration_minutes: number;
  equipment: string[];
  days: WorkoutDay[];
}

/**
 * Workout day within a plan
 */
export interface WorkoutDay {
  day_number: number;
  name: string;
  exercises: Exercise[];
}

/**
 * Exercise within a workout day
 */
export interface Exercise {
  name: string;
  sets: number;
  reps: string;
  rest_seconds: number;
  notes?: string;
}

/**
 * Onboarding Meal Plan structure
 * Generated by diet planning agent during onboarding
 * This is a preview/proposal plan shown to user for approval
 */
export interface OnboardingMealPlan {
  diet_type: string;
  meal_frequency: number;
  daily_calories: number;
  macros: MacroBreakdown;
  sample_meals: SampleMeal[];
}

/**
 * Macro breakdown for meal plan
 */
export interface MacroBreakdown {
  protein_g: number;
  carbs_g: number;
  fats_g: number;
}

/**
 * Sample meal within a meal plan
 */
export interface SampleMeal {
  meal_number: number;
  name: string;
  calories: number;
  protein_g: number;
  carbs_g: number;
  fats_g: number;
  foods: string[];
}

/**
 * Onboarding complete response
 * Returned by POST /api/v1/onboarding/complete
 * Contains created profile information
 */
export interface OnboardingCompleteResponse {
  profile_id: string;
  user_id: string;
  fitness_level: string;
  is_locked: boolean;
  onboarding_complete: boolean;
  message: string;
}
