"""Initial schema

Revision ID: 0c90191dbca7
Revises: 
Create Date: 2026-01-29 19:09:54.761872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c90191dbca7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_provider', 'oauth_provider_user_id', name='unique_oauth_user')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_oauth', 'users', ['oauth_provider', 'oauth_provider_user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('onboarding_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('step_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_onboarding')
    )
    op.create_index('idx_onboarding_user', 'onboarding_states', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('fitness_level', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_profile')
    )
    op.create_index('idx_profile_user', 'user_profiles', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('dietary_preferences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('diet_type', sa.String(length=50), nullable=False),
    sa.Column('allergies', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('intolerances', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('dislikes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='unique_profile_dietary')
    )
    op.create_index('idx_dietary_preferences_profile', 'dietary_preferences', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('fitness_goals',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_body_fat_percentage', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fitness_goals_profile', 'fitness_goals', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('hydration_preferences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('daily_water_target_ml', sa.Integer(), nullable=False),
    sa.Column('reminder_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('enable_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='unique_profile_hydration')
    )
    op.create_index('idx_hydration_preferences_profile', 'hydration_preferences', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('lifestyle_baselines',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('energy_level BETWEEN 1 AND 10', name='valid_energy_level'),
    sa.CheckConstraint('sleep_quality BETWEEN 1 AND 10', name='valid_sleep_quality'),
    sa.CheckConstraint('stress_level BETWEEN 1 AND 10', name='valid_stress_level'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='unique_profile_lifestyle')
    )
    op.create_index('idx_lifestyle_baselines_profile', 'lifestyle_baselines', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('meal_plans',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=False),
    sa.Column('protein_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('carbs_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fats_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('protein_percentage + carbs_percentage + fats_percentage = 100', name='valid_macro_sum'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='unique_profile_meal_plan')
    )
    op.create_index('idx_meal_plans_profile', 'meal_plans', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('meal_schedules',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('meal_name', sa.String(length=100), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('enable_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meal_schedules_profile', 'meal_schedules', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('physical_constraints',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_physical_constraints_profile', 'physical_constraints', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_profile_versions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_versions', 'user_profile_versions', ['profile_id', 'version_number'], unique=False)
    op.create_table('workout_schedules',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('enable_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_schedules_profile', 'workout_schedules', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workout_schedules_profile', table_name='workout_schedules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('workout_schedules')
    op.drop_index('idx_profile_versions', table_name='user_profile_versions')
    op.drop_table('user_profile_versions')
    op.drop_index('idx_physical_constraints_profile', table_name='physical_constraints', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('physical_constraints')
    op.drop_index('idx_meal_schedules_profile', table_name='meal_schedules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('meal_schedules')
    op.drop_index('idx_meal_plans_profile', table_name='meal_plans', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('meal_plans')
    op.drop_index('idx_lifestyle_baselines_profile', table_name='lifestyle_baselines', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('lifestyle_baselines')
    op.drop_index('idx_hydration_preferences_profile', table_name='hydration_preferences', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('hydration_preferences')
    op.drop_index('idx_fitness_goals_profile', table_name='fitness_goals', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('fitness_goals')
    op.drop_index('idx_dietary_preferences_profile', table_name='dietary_preferences', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('dietary_preferences')
    op.drop_index('idx_profile_user', table_name='user_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('user_profiles')
    op.drop_index('idx_onboarding_user', table_name='onboarding_states', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('onboarding_states')
    op.drop_index('idx_users_oauth', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
