"""add workout_logs table

Revision ID: 5aca3703586c
Revises: 775f4d7d5da2
Create Date: 2026-02-08 23:29:45.275456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aca3703586c'
down_revision: Union[str, Sequence[str], None] = '775f4d7d5da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise', sa.String(length=255), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_logs_logged_at', 'workout_logs', ['logged_at'], unique=False, postgresql_ops={'logged_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_workout_logs_user_id', 'workout_logs', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_workout_logs_user_logged', 'workout_logs', ['user_id', 'logged_at'], unique=False, postgresql_ops={'logged_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    # Removed: op.drop_table('test_models') - test table should not be in production migrations
    op.drop_index(op.f('idx_chat_sessions_user'), table_name='chat_sessions', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_chat_sessions_user', 'chat_sessions', ['user_id', 'started_at'], unique=False, postgresql_ops={'started_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('idx_conversation_user_created'), table_name='conversation_messages')
    op.create_index('idx_conversation_user_created', 'conversation_messages', ['user_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_workout_plans_updated'), table_name='workout_plans', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_workout_plans_updated', 'workout_plans', ['updated_at'], unique=False, postgresql_ops={'updated_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workout_plans_updated', table_name='workout_plans', postgresql_ops={'updated_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_workout_plans_updated'), 'workout_plans', [sa.literal_column('updated_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_conversation_user_created', table_name='conversation_messages', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_conversation_user_created'), 'conversation_messages', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_chat_sessions_user', table_name='chat_sessions', postgresql_ops={'started_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_chat_sessions_user'), 'chat_sessions', ['user_id', sa.literal_column('started_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    # Removed: test_models table recreation - test table should not be in production migrations
    op.drop_index('idx_workout_logs_user_logged', table_name='workout_logs', postgresql_ops={'logged_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_workout_logs_user_id', table_name='workout_logs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_workout_logs_logged_at', table_name='workout_logs', postgresql_ops={'logged_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('workout_logs')
    # ### end Alembic commands ###
