"""add conversation messages

Revision ID: 775f4d7d5da2
Revises: 7c49238b5ab6
Create Date: 2026-02-06 17:51:30.135179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775f4d7d5da2'
down_revision: Union[str, Sequence[str], None] = '7c49238b5ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='valid_conversation_role'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_user_created', 'conversation_messages', ['user_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_chat_sessions_user'), table_name='chat_sessions', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_chat_sessions_user', 'chat_sessions', ['user_id', 'started_at'], unique=False, postgresql_ops={'started_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('idx_workout_plans_updated'), table_name='workout_plans', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_workout_plans_updated', 'workout_plans', ['updated_at'], unique=False, postgresql_ops={'updated_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workout_plans_updated', table_name='workout_plans', postgresql_ops={'updated_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_workout_plans_updated'), 'workout_plans', [sa.literal_column('updated_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_chat_sessions_user', table_name='chat_sessions', postgresql_ops={'started_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_chat_sessions_user'), 'chat_sessions', ['user_id', sa.literal_column('started_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_conversation_user_created', table_name='conversation_messages', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
