"""initial_schema

Revision ID: 7c49238b5ab6
Revises: 
Create Date: 2026-02-02 12:06:31.533603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c49238b5ab6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_hindi', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cuisine_type', sa.String(length=50), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('dish_category', sa.String(length=50), nullable=True),
    sa.Column('serving_size_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('calories', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fats_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=False),
    sa.Column('is_dairy_free', sa.Boolean(), nullable=False),
    sa.Column('is_nut_free', sa.Boolean(), nullable=False),
    sa.Column('contains_allergens', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('popularity_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("difficulty_level IN ('easy', 'medium', 'hard')", name='valid_difficulty'),
    sa.CheckConstraint("meal_type IN ('breakfast', 'lunch', 'dinner', 'snack', 'pre_workout', 'post_workout')", name='valid_meal_type'),
    sa.CheckConstraint('calories > 0 AND calories < 2000', name='valid_calories'),
    sa.CheckConstraint('cook_time_minutes >= 0 AND cook_time_minutes <= 240', name='valid_cook_time'),
    sa.CheckConstraint('prep_time_minutes >= 0 AND prep_time_minutes <= 180', name='valid_prep_time'),
    sa.CheckConstraint('protein_g >= 0 AND carbs_g >= 0 AND fats_g >= 0', name='valid_macros'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dishes_cuisine', 'dishes', ['cuisine_type'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_index('idx_dishes_dietary', 'dishes', ['is_vegetarian', 'is_vegan'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_index('idx_dishes_meal_type', 'dishes', ['meal_type'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_index('idx_dishes_nutrition', 'dishes', ['calories', 'protein_g'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_table('exercise_library',
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('exercise_slug', sa.String(length=255), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('primary_muscle_group', sa.String(length=100), nullable=False),
    sa.Column('secondary_muscle_groups', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('equipment_required', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('gif_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('is_compound', sa.Boolean(), nullable=False),
    sa.Column('is_unilateral', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("difficulty_level IN ('beginner', 'intermediate', 'advanced')", name='valid_difficulty'),
    sa.CheckConstraint("exercise_type IN ('strength', 'cardio', 'flexibility', 'plyometric', 'olympic')", name='valid_exercise_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_name'),
    sa.UniqueConstraint('exercise_slug')
    )
    op.create_index('idx_exercise_library_difficulty', 'exercise_library', ['difficulty_level'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_exercise_library_equipment', 'exercise_library', ['equipment_required'], unique=False, postgresql_using='gin', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_exercise_library_muscle', 'exercise_library', ['primary_muscle_group'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_exercise_library_type', 'exercise_library', ['exercise_type'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('ingredients',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_hindi', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('calories_per_100g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('protein_per_100g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('carbs_per_100g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fats_per_100g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('typical_unit', sa.String(length=20), nullable=False),
    sa.Column('is_allergen', sa.Boolean(), nullable=False),
    sa.Column('allergen_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('vegetable', 'fruit', 'protein', 'grain', 'dairy', 'spice', 'oil', 'other')", name='valid_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_ingredients_allergen', 'ingredients', ['is_allergen', 'allergen_type'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_index('idx_ingredients_category', 'ingredients', ['category'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_provider', 'oauth_provider_user_id', name='unique_oauth_user')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_oauth', 'users', ['oauth_provider', 'oauth_provider_user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("session_type IN ('general', 'workout', 'meal', 'supplement', 'tracking')", name='valid_session_type'),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned')", name='valid_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_active', 'chat_sessions', ['user_id', 'status'], unique=False, postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.create_index('idx_chat_sessions_user', 'chat_sessions', ['user_id', 'started_at'], unique=False, postgresql_ops={'started_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('dish_ingredients',
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('preparation_note', sa.String(length=200), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='valid_quantity'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id', 'ingredient_id', name='unique_dish_ingredient')
    )
    op.create_index('idx_dish_ingredients_dish', 'dish_ingredients', ['dish_id'], unique=False)
    op.create_index('idx_dish_ingredients_ingredient', 'dish_ingredients', ['ingredient_id'], unique=False)
    op.create_table('onboarding_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('step_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_onboarding')
    )
    op.create_index('idx_onboarding_user', 'onboarding_states', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('fitness_level', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_profile')
    )
    op.create_index('idx_profile_user', 'user_profiles', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('workout_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('plan_description', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('plan_rationale', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('days_per_week >= 1 AND days_per_week <= 7', name='valid_days_per_week'),
    sa.CheckConstraint('duration_weeks >= 1 AND duration_weeks <= 52', name='valid_duration'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_workout_plan')
    )
    op.create_index('idx_workout_plans_updated', 'workout_plans', ['updated_at'], unique=False, postgresql_ops={'updated_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_workout_plans_user_id', 'workout_plans', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("agent_type IS NULL OR agent_type IN ('workout_planning', 'diet_planning', 'supplement_guidance', 'tracking_adjustment', 'scheduling_reminder', 'conversational')", name='valid_agent_type'),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='valid_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_session', 'chat_messages', ['session_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('dietary_preferences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('diet_type', sa.String(length=50), nullable=False),
    sa.Column('allergies', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('intolerances', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('dislikes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='unique_profile_dietary')
    )
    op.create_index('idx_dietary_preferences_profile', 'dietary_preferences', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('fitness_goals',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_body_fat_percentage', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fitness_goals_profile', 'fitness_goals', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('hydration_preferences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('daily_water_target_ml', sa.Integer(), nullable=False),
    sa.Column('reminder_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('enable_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='unique_profile_hydration')
    )
    op.create_index('idx_hydration_preferences_profile', 'hydration_preferences', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('lifestyle_baselines',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('energy_level BETWEEN 1 AND 10', name='valid_energy_level'),
    sa.CheckConstraint('sleep_quality BETWEEN 1 AND 10', name='valid_sleep_quality'),
    sa.CheckConstraint('stress_level BETWEEN 1 AND 10', name='valid_stress_level'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='unique_profile_lifestyle')
    )
    op.create_index('idx_lifestyle_baselines_profile', 'lifestyle_baselines', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('meal_plans',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=False),
    sa.Column('protein_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('carbs_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fats_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('protein_percentage + carbs_percentage + fats_percentage = 100', name='valid_macro_sum'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='unique_profile_meal_plan')
    )
    op.create_index('idx_meal_plans_profile', 'meal_plans', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('meal_schedules',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('meal_name', sa.String(length=100), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('enable_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meal_schedules_profile', 'meal_schedules', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('meal_templates',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('generation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('week_number BETWEEN 1 AND 4', name='valid_week_number'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'week_number', name='unique_profile_week')
    )
    op.create_index('idx_meal_templates_active', 'meal_templates', ['profile_id', 'is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.create_index('idx_meal_templates_profile', 'meal_templates', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('physical_constraints',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_physical_constraints_profile', 'physical_constraints', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_profile_versions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_versions', 'user_profile_versions', ['profile_id', 'version_number'], unique=False)
    op.create_table('workout_days',
    sa.Column('workout_plan_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(length=255), nullable=False),
    sa.Column('muscle_groups', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("workout_type IN ('strength', 'cardio', 'hiit', 'active_recovery', 'rest')", name='valid_workout_type'),
    sa.CheckConstraint('day_number >= 1 AND day_number <= 7', name='valid_day_number'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_plan_id', 'day_number', name='unique_plan_day')
    )
    op.create_index('idx_workout_days_plan', 'workout_days', ['workout_plan_id', 'day_number'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('workout_schedules',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('enable_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_schedules_profile', 'workout_schedules', ['profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('template_meals',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('meal_schedule_id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('alternative_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('alternative_order BETWEEN 1 AND 5', name='valid_alternative_order'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='valid_day_of_week'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_schedule_id'], ['meal_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['meal_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_meals_day', 'template_meals', ['template_id', 'day_of_week'], unique=False)
    op.create_index('idx_template_meals_dish', 'template_meals', ['dish_id'], unique=False)
    op.create_index('idx_template_meals_primary', 'template_meals', ['template_id', 'is_primary'], unique=False, postgresql_where=sa.text('is_primary = true'))
    op.create_index('idx_template_meals_schedule', 'template_meals', ['meal_schedule_id'], unique=False)
    op.create_index('idx_template_meals_template', 'template_meals', ['template_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('workout_day_id', sa.UUID(), nullable=False),
    sa.Column('exercise_library_id', sa.UUID(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('reps_target', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight_progression_type', sa.String(length=50), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("weight_progression_type IS NULL OR weight_progression_type IN ('linear', 'percentage', 'rpe_based', 'none')", name='valid_progression'),
    sa.CheckConstraint('(reps_target IS NOT NULL AND reps_target >= 1 AND reps_target <= 100) OR (reps_min IS NOT NULL AND reps_max IS NOT NULL AND reps_min <= reps_max)', name='valid_reps'),
    sa.CheckConstraint('rest_seconds >= 0 AND rest_seconds <= 600', name='valid_rest'),
    sa.CheckConstraint('sets >= 1 AND sets <= 20', name='valid_sets'),
    sa.ForeignKeyConstraint(['exercise_library_id'], ['exercise_library.id'], ),
    sa.ForeignKeyConstraint(['workout_day_id'], ['workout_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_day_id', 'exercise_order', name='unique_day_exercise_order')
    )
    op.create_index('idx_workout_exercises_day', 'workout_exercises', ['workout_day_id', 'exercise_order'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_workout_exercises_library', 'workout_exercises', ['exercise_library_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workout_exercises_library', table_name='workout_exercises', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_workout_exercises_day', table_name='workout_exercises', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('workout_exercises')
    op.drop_index('idx_template_meals_template', table_name='template_meals')
    op.drop_index('idx_template_meals_schedule', table_name='template_meals')
    op.drop_index('idx_template_meals_primary', table_name='template_meals', postgresql_where=sa.text('is_primary = true'))
    op.drop_index('idx_template_meals_dish', table_name='template_meals')
    op.drop_index('idx_template_meals_day', table_name='template_meals')
    op.drop_table('template_meals')
    op.drop_index('idx_workout_schedules_profile', table_name='workout_schedules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('workout_schedules')
    op.drop_index('idx_workout_days_plan', table_name='workout_days', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('workout_days')
    op.drop_index('idx_profile_versions', table_name='user_profile_versions')
    op.drop_table('user_profile_versions')
    op.drop_index('idx_physical_constraints_profile', table_name='physical_constraints', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('physical_constraints')
    op.drop_index('idx_meal_templates_profile', table_name='meal_templates', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_meal_templates_active', table_name='meal_templates', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_table('meal_templates')
    op.drop_index('idx_meal_schedules_profile', table_name='meal_schedules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('meal_schedules')
    op.drop_index('idx_meal_plans_profile', table_name='meal_plans', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('meal_plans')
    op.drop_index('idx_lifestyle_baselines_profile', table_name='lifestyle_baselines', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('lifestyle_baselines')
    op.drop_index('idx_hydration_preferences_profile', table_name='hydration_preferences', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('hydration_preferences')
    op.drop_index('idx_fitness_goals_profile', table_name='fitness_goals', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('fitness_goals')
    op.drop_index('idx_dietary_preferences_profile', table_name='dietary_preferences', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('dietary_preferences')
    op.drop_index('idx_chat_messages_session', table_name='chat_messages', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('chat_messages')
    op.drop_index('idx_workout_plans_user_id', table_name='workout_plans', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_workout_plans_updated', table_name='workout_plans', postgresql_ops={'updated_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('workout_plans')
    op.drop_index('idx_profile_user', table_name='user_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('user_profiles')
    op.drop_index('idx_onboarding_user', table_name='onboarding_states', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('onboarding_states')
    op.drop_index('idx_dish_ingredients_ingredient', table_name='dish_ingredients')
    op.drop_index('idx_dish_ingredients_dish', table_name='dish_ingredients')
    op.drop_table('dish_ingredients')
    op.drop_index('idx_chat_sessions_user', table_name='chat_sessions', postgresql_ops={'started_at': 'DESC'}, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_chat_sessions_active', table_name='chat_sessions', postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.drop_table('chat_sessions')
    op.drop_index('idx_users_oauth', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index('idx_ingredients_category', table_name='ingredients', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_index('idx_ingredients_allergen', table_name='ingredients', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_table('ingredients')
    op.drop_index('idx_exercise_library_type', table_name='exercise_library', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_exercise_library_muscle', table_name='exercise_library', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_exercise_library_equipment', table_name='exercise_library', postgresql_using='gin', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_exercise_library_difficulty', table_name='exercise_library', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('exercise_library')
    op.drop_index('idx_dishes_nutrition', table_name='dishes', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_index('idx_dishes_meal_type', table_name='dishes', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_index('idx_dishes_dietary', table_name='dishes', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_index('idx_dishes_cuisine', table_name='dishes', postgresql_where=sa.text('deleted_at IS NULL AND is_active = true'))
    op.drop_table('dishes')
    # ### end Alembic commands ###
