"""
Comprehensive dish seed data for meal planning system.

This file contains 200+ Indian dishes across all meal types with:
- Accurate nutritional information
- Ingredient lists with quantities
- Preparation and cooking times
- Dietary classifications
"""

# Breakfast Dishes (50+ dishes)
BREAKFAST_DISHES = [
    {
        'name': 'Egg Omelette with Multigrain Toast',
        'name_hindi': 'अंडे का ऑमलेट',
        'description': 'Protein-rich omelette with whole grain toast',
        'cuisine_type': 'continental',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 250,
        'calories': 350,
        'protein_g': 25,
        'carbs_g': 30,
        'fats_g': 15,
        'fiber_g': 4,
        'prep_time_minutes': 5,
        'cook_time_minutes': 10,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': False,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': ['eggs', 'wheat'],
        'popularity_score': 95,
        'ingredients': [
            {'name': 'eggs', 'quantity': 3, 'unit': 'piece'},
            {'name': 'multigrain_bread', 'quantity': 2, 'unit': 'slice'},
            {'name': 'olive_oil', 'quantity': 5, 'unit': 'ml'},
            {'name': 'onion', 'quantity': 30, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 30, 'unit': 'g'},
            {'name': 'salt', 'quantity': 2, 'unit': 'g'},
            {'name': 'black_pepper', 'quantity': 1, 'unit': 'g'},
        ]
    },
    {
        'name': 'Oats Porridge with Banana and Almonds',
        'name_hindi': 'ओट्स दलिया',
        'description': 'Healthy oats with fresh fruits and nuts',
        'cuisine_type': 'continental',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 300,
        'calories': 380,
        'protein_g': 12,
        'carbs_g': 55,
        'fats_g': 12,
        'fiber_g': 8,
        'prep_time_minutes': 5,
        'cook_time_minutes': 10,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': False,
        'is_nut_free': False,
        'contains_allergens': ['dairy', 'tree_nuts'],
        'popularity_score': 90,
        'ingredients': [
            {'name': 'rolled_oats', 'quantity': 60, 'unit': 'g'},
            {'name': 'milk', 'quantity': 200, 'unit': 'ml'},
            {'name': 'banana', 'quantity': 1, 'unit': 'piece'},
            {'name': 'almonds', 'quantity': 10, 'unit': 'g'},
            {'name': 'honey', 'quantity': 10, 'unit': 'ml'},
            {'name': 'cinnamon', 'quantity': 1, 'unit': 'g'},
        ]
    },
    {
        'name': 'Paneer Paratha with Curd',
        'name_hindi': 'पनीर पराठा',
        'description': 'Stuffed flatbread with cottage cheese',
        'cuisine_type': 'north_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 350,
        'calories': 450,
        'protein_g': 20,
        'carbs_g': 50,
        'fats_g': 18,
        'fiber_g': 5,
        'prep_time_minutes': 15,
        'cook_time_minutes': 15,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': False,
        'is_dairy_free': False,
        'is_nut_free': True,
        'contains_allergens': ['wheat', 'dairy'],
        'popularity_score': 92,
        'ingredients': [
            {'name': 'whole_wheat_flour', 'quantity': 100, 'unit': 'g'},
            {'name': 'paneer', 'quantity': 80, 'unit': 'g'},
            {'name': 'curd', 'quantity': 100, 'unit': 'g'},
            {'name': 'ghee', 'quantity': 15, 'unit': 'ml'},
            {'name': 'green_chili', 'quantity': 5, 'unit': 'g'},
            {'name': 'coriander_leaves', 'quantity': 10, 'unit': 'g'},
            {'name': 'cumin_powder', 'quantity': 2, 'unit': 'g'},
            {'name': 'salt', 'quantity': 3, 'unit': 'g'},
        ]
    },
    {
        'name': 'Poha with Peanuts',
        'name_hindi': 'पोहा',
        'description': 'Flattened rice with vegetables and peanuts',
        'cuisine_type': 'north_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 250,
        'calories': 320,
        'protein_g': 8,
        'carbs_g': 52,
        'fats_g': 10,
        'fiber_g': 4,
        'prep_time_minutes': 10,
        'cook_time_minutes': 10,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': False,
        'contains_allergens': ['peanuts'],
        'popularity_score': 88,
        'ingredients': [
            {'name': 'poha', 'quantity': 100, 'unit': 'g'},
            {'name': 'peanuts', 'quantity': 20, 'unit': 'g'},
            {'name': 'onion', 'quantity': 40, 'unit': 'g'},
            {'name': 'potato', 'quantity': 50, 'unit': 'g'},
            {'name': 'green_chili', 'quantity': 5, 'unit': 'g'},
            {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'},
            {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'},
            {'name': 'turmeric', 'quantity': 1, 'unit': 'g'},
            {'name': 'lemon_juice', 'quantity': 10, 'unit': 'ml'},
            {'name': 'oil', 'quantity': 10, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Idli with Sambar',
        'name_hindi': 'इडली सांभर',
        'description': 'Steamed rice cakes with lentil stew',
        'cuisine_type': 'south_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 300,
        'calories': 280,
        'protein_g': 12,
        'carbs_g': 50,
        'fats_g': 4,
        'fiber_g': 6,
        'prep_time_minutes': 20,
        'cook_time_minutes': 20,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 94,
        'ingredients': [
            {'name': 'idli_batter', 'quantity': 150, 'unit': 'g'},
            {'name': 'toor_dal', 'quantity': 30, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 50, 'unit': 'g'},
            {'name': 'drumstick', 'quantity': 50, 'unit': 'g'},
            {'name': 'tamarind', 'quantity': 10, 'unit': 'g'},
            {'name': 'sambar_powder', 'quantity': 5, 'unit': 'g'},
            {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'},
            {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'},
        ]
    },
    {
        'name': 'Masala Dosa',
        'name_hindi': 'मसाला डोसा',
        'description': 'Crispy rice crepe with spiced potato filling',
        'cuisine_type': 'south_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 350,
        'calories': 420,
        'protein_g': 10,
        'carbs_g': 65,
        'fats_g': 14,
        'fiber_g': 5,
        'prep_time_minutes': 15,
        'cook_time_minutes': 20,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 96,
        'ingredients': [
            {'name': 'dosa_batter', 'quantity': 150, 'unit': 'g'},
            {'name': 'potato', 'quantity': 150, 'unit': 'g'},
            {'name': 'onion', 'quantity': 40, 'unit': 'g'},
            {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'},
            {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'},
            {'name': 'turmeric', 'quantity': 1, 'unit': 'g'},
            {'name': 'oil', 'quantity': 15, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Upma with Vegetables',
        'name_hindi': 'उपमा',
        'description': 'Semolina porridge with mixed vegetables',
        'cuisine_type': 'south_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 280,
        'calories': 310,
        'protein_g': 9,
        'carbs_g': 48,
        'fats_g': 10,
        'fiber_g': 4,
        'prep_time_minutes': 10,
        'cook_time_minutes': 15,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': False,
        'is_dairy_free': True,
        'is_nut_free': False,
        'contains_allergens': ['wheat'],
        'popularity_score': 85,
        'ingredients': [
            {'name': 'semolina', 'quantity': 80, 'unit': 'g'},
            {'name': 'carrot', 'quantity': 40, 'unit': 'g'},
            {'name': 'peas', 'quantity': 30, 'unit': 'g'},
            {'name': 'onion', 'quantity': 30, 'unit': 'g'},
            {'name': 'cashews', 'quantity': 10, 'unit': 'g'},
            {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'},
            {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'},
            {'name': 'oil', 'quantity': 12, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Aloo Paratha with Butter',
        'name_hindi': 'आलू पराठा',
        'description': 'Potato-stuffed flatbread with butter',
        'cuisine_type': 'north_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 320,
        'calories': 410,
        'protein_g': 10,
        'carbs_g': 58,
        'fats_g': 16,
        'fiber_g': 5,
        'prep_time_minutes': 15,
        'cook_time_minutes': 15,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': False,
        'is_dairy_free': False,
        'is_nut_free': True,
        'contains_allergens': ['wheat', 'dairy'],
        'popularity_score': 93,
        'ingredients': [
            {'name': 'whole_wheat_flour', 'quantity': 100, 'unit': 'g'},
            {'name': 'potato', 'quantity': 120, 'unit': 'g'},
            {'name': 'butter', 'quantity': 15, 'unit': 'g'},
            {'name': 'green_chili', 'quantity': 5, 'unit': 'g'},
            {'name': 'coriander_leaves', 'quantity': 10, 'unit': 'g'},
            {'name': 'cumin_powder', 'quantity': 2, 'unit': 'g'},
            {'name': 'salt', 'quantity': 3, 'unit': 'g'},
        ]
    },
    {
        'name': 'Scrambled Eggs with Whole Wheat Toast',
        'name_hindi': 'भुर्जी',
        'description': 'Spiced scrambled eggs with toast',
        'cuisine_type': 'continental',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 240,
        'calories': 340,
        'protein_g': 24,
        'carbs_g': 28,
        'fats_g': 14,
        'fiber_g': 4,
        'prep_time_minutes': 5,
        'cook_time_minutes': 8,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': False,
        'is_dairy_free': False,
        'is_nut_free': True,
        'contains_allergens': ['eggs', 'wheat', 'dairy'],
        'popularity_score': 91,
        'ingredients': [
            {'name': 'eggs', 'quantity': 3, 'unit': 'piece'},
            {'name': 'whole_wheat_bread', 'quantity': 2, 'unit': 'slice'},
            {'name': 'milk', 'quantity': 30, 'unit': 'ml'},
            {'name': 'butter', 'quantity': 10, 'unit': 'g'},
            {'name': 'onion', 'quantity': 20, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 30, 'unit': 'g'},
            {'name': 'salt', 'quantity': 2, 'unit': 'g'},
            {'name': 'black_pepper', 'quantity': 1, 'unit': 'g'},
        ]
    },
    {
        'name': 'Moong Dal Cheela',
        'name_hindi': 'मूंग दाल चीला',
        'description': 'Savory lentil pancake',
        'cuisine_type': 'north_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 250,
        'calories': 290,
        'protein_g': 18,
        'carbs_g': 38,
        'fats_g': 8,
        'fiber_g': 7,
        'prep_time_minutes': 120,
        'cook_time_minutes': 15,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 87,
        'ingredients': [
            {'name': 'moong_dal', 'quantity': 100, 'unit': 'g'},
            {'name': 'onion', 'quantity': 30, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 30, 'unit': 'g'},
            {'name': 'green_chili', 'quantity': 5, 'unit': 'g'},
            {'name': 'ginger', 'quantity': 5, 'unit': 'g'},
            {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'},
            {'name': 'oil', 'quantity': 10, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Vegetable Sandwich with Cheese',
        'name_hindi': 'वेज सैंडविच',
        'description': 'Grilled vegetable sandwich with cheese',
        'cuisine_type': 'continental',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 280,
        'calories': 380,
        'protein_g': 16,
        'carbs_g': 45,
        'fats_g': 15,
        'fiber_g': 6,
        'prep_time_minutes': 10,
        'cook_time_minutes': 10,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': False,
        'is_dairy_free': False,
        'is_nut_free': True,
        'contains_allergens': ['wheat', 'dairy'],
        'popularity_score': 89,
        'ingredients': [
            {'name': 'whole_wheat_bread', 'quantity': 4, 'unit': 'slice'},
            {'name': 'cheese', 'quantity': 40, 'unit': 'g'},
            {'name': 'cucumber', 'quantity': 40, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 40, 'unit': 'g'},
            {'name': 'onion', 'quantity': 20, 'unit': 'g'},
            {'name': 'butter', 'quantity': 10, 'unit': 'g'},
            {'name': 'black_pepper', 'quantity': 1, 'unit': 'g'},
        ]
    },
    {
        'name': 'Besan Cheela',
        'name_hindi': 'बेसन चीला',
        'description': 'Gram flour pancake with vegetables',
        'cuisine_type': 'north_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 240,
        'calories': 300,
        'protein_g': 14,
        'carbs_g': 40,
        'fats_g': 10,
        'fiber_g': 6,
        'prep_time_minutes': 10,
        'cook_time_minutes': 15,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 86,
        'ingredients': [
            {'name': 'besan', 'quantity': 100, 'unit': 'g'},
            {'name': 'onion', 'quantity': 40, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 30, 'unit': 'g'},
            {'name': 'green_chili', 'quantity': 5, 'unit': 'g'},
            {'name': 'coriander_leaves', 'quantity': 10, 'unit': 'g'},
            {'name': 'turmeric', 'quantity': 1, 'unit': 'g'},
            {'name': 'oil', 'quantity': 12, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Greek Yogurt with Berries and Granola',
        'name_hindi': 'ग्रीक दही',
        'description': 'High-protein yogurt with fresh berries',
        'cuisine_type': 'continental',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 300,
        'calories': 340,
        'protein_g': 20,
        'carbs_g': 45,
        'fats_g': 10,
        'fiber_g': 5,
        'prep_time_minutes': 5,
        'cook_time_minutes': 0,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': False,
        'is_nut_free': False,
        'contains_allergens': ['dairy', 'tree_nuts'],
        'popularity_score': 88,
        'ingredients': [
            {'name': 'greek_yogurt', 'quantity': 200, 'unit': 'g'},
            {'name': 'mixed_berries', 'quantity': 80, 'unit': 'g'},
            {'name': 'granola', 'quantity': 40, 'unit': 'g'},
            {'name': 'honey', 'quantity': 10, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Rava Idli',
        'name_hindi': 'रवा इडली',
        'description': 'Instant semolina steamed cakes',
        'cuisine_type': 'south_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 250,
        'calories': 270,
        'protein_g': 8,
        'carbs_g': 48,
        'fats_g': 6,
        'fiber_g': 3,
        'prep_time_minutes': 10,
        'cook_time_minutes': 15,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': False,
        'is_dairy_free': True,
        'is_nut_free': False,
        'contains_allergens': ['wheat'],
        'popularity_score': 84,
        'ingredients': [
            {'name': 'semolina', 'quantity': 100, 'unit': 'g'},
            {'name': 'curd', 'quantity': 50, 'unit': 'g'},
            {'name': 'cashews', 'quantity': 10, 'unit': 'g'},
            {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'},
            {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'},
            {'name': 'oil', 'quantity': 8, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Methi Thepla',
        'name_hindi': 'मेथी थेपला',
        'description': 'Fenugreek flatbread',
        'cuisine_type': 'north_indian',
        'meal_type': 'breakfast',
        'dish_category': 'main_course',
        'serving_size_g': 200,
        'calories': 320,
        'protein_g': 10,
        'carbs_g': 50,
        'fats_g': 10,
        'fiber_g': 6,
        'prep_time_minutes': 15,
        'cook_time_minutes': 20,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': False,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': ['wheat'],
        'popularity_score': 82,
        'ingredients': [
            {'name': 'whole_wheat_flour', 'quantity': 100, 'unit': 'g'},
            {'name': 'fenugreek_leaves', 'quantity': 50, 'unit': 'g'},
            {'name': 'curd', 'quantity': 30, 'unit': 'g'},
            {'name': 'turmeric', 'quantity': 1, 'unit': 'g'},
            {'name': 'red_chili_powder', 'quantity': 2, 'unit': 'g'},
            {'name': 'oil', 'quantity': 12, 'unit': 'ml'},
        ]
    },
    # Additional 40+ breakfast dishes to reach 50+ total
    {'name': 'Sabudana Khichdi', 'name_hindi': 'साबूदाना खिचड़ी', 'description': 'Tapioca pearl dish', 'cuisine_type': 'north_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 250, 'calories': 340, 'protein_g': 6, 'carbs_g': 62, 'fats_g': 10, 'fiber_g': 2, 'prep_time_minutes': 120, 'cook_time_minutes': 15, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': ['peanuts'], 'popularity_score': 84, 'ingredients': [{'name': 'sabudana', 'quantity': 100, 'unit': 'g'}, {'name': 'peanuts', 'quantity': 30, 'unit': 'g'}, {'name': 'potato', 'quantity': 50, 'unit': 'g'}, {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'green_chili', 'quantity': 5, 'unit': 'g'}, {'name': 'oil', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Vermicelli Upma', 'name_hindi': 'सेवई उपमा', 'description': 'Savory vermicelli', 'cuisine_type': 'south_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 260, 'calories': 310, 'protein_g': 8, 'carbs_g': 52, 'fats_g': 9, 'fiber_g': 3, 'prep_time_minutes': 8, 'cook_time_minutes': 12, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': ['wheat'], 'popularity_score': 83, 'ingredients': [{'name': 'vermicelli', 'quantity': 100, 'unit': 'g'}, {'name': 'onion', 'quantity': 30, 'unit': 'g'}, {'name': 'peas', 'quantity': 30, 'unit': 'g'}, {'name': 'cashews', 'quantity': 10, 'unit': 'g'}, {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'oil', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Bread Pakora', 'name_hindi': 'ब्रेड पकोड़ा', 'description': 'Fried bread fritters', 'cuisine_type': 'north_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 200, 'calories': 380, 'protein_g': 12, 'carbs_g': 48, 'fats_g': 16, 'fiber_g': 4, 'prep_time_minutes': 10, 'cook_time_minutes': 15, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['wheat'], 'popularity_score': 86, 'ingredients': [{'name': 'bread', 'quantity': 4, 'unit': 'slice'}, {'name': 'besan', 'quantity': 60, 'unit': 'g'}, {'name': 'potato', 'quantity': 80, 'unit': 'g'}, {'name': 'green_chili', 'quantity': 5, 'unit': 'g'}, {'name': 'oil', 'quantity': 20, 'unit': 'ml'}]},
    {'name': 'Pongal', 'name_hindi': 'पोंगल', 'description': 'Rice and lentil porridge', 'cuisine_type': 'south_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 300, 'calories': 350, 'protein_g': 12, 'carbs_g': 58, 'fats_g': 10, 'fiber_g': 5, 'prep_time_minutes': 10, 'cook_time_minutes': 25, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': [], 'popularity_score': 85, 'ingredients': [{'name': 'rice', 'quantity': 80, 'unit': 'g'}, {'name': 'moong_dal', 'quantity': 40, 'unit': 'g'}, {'name': 'black_pepper', 'quantity': 2, 'unit': 'g'}, {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'cashews', 'quantity': 10, 'unit': 'g'}, {'name': 'ghee', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Pesarattu', 'name_hindi': 'पेसरट्टू', 'description': 'Green gram dosa', 'cuisine_type': 'south_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 280, 'calories': 290, 'protein_g': 16, 'carbs_g': 42, 'fats_g': 8, 'fiber_g': 8, 'prep_time_minutes': 120, 'cook_time_minutes': 15, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 82, 'ingredients': [{'name': 'moong_dal', 'quantity': 120, 'unit': 'g'}, {'name': 'rice', 'quantity': 40, 'unit': 'g'}, {'name': 'ginger', 'quantity': 10, 'unit': 'g'}, {'name': 'green_chili', 'quantity': 5, 'unit': 'g'}, {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'oil', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Appam with Stew', 'name_hindi': 'अप्पम', 'description': 'Rice pancake with vegetable stew', 'cuisine_type': 'south_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 320, 'calories': 360, 'protein_g': 10, 'carbs_g': 58, 'fats_g': 12, 'fiber_g': 5, 'prep_time_minutes': 180, 'cook_time_minutes': 20, 'difficulty_level': 'hard', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 87, 'ingredients': [{'name': 'rice', 'quantity': 100, 'unit': 'g'}, {'name': 'coconut', 'quantity': 40, 'unit': 'g'}, {'name': 'mixed_vegetables', 'quantity': 100, 'unit': 'g'}, {'name': 'coconut_milk', 'quantity': 80, 'unit': 'ml'}, {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'}]},
    {'name': 'Puttu with Kadala Curry', 'name_hindi': 'पुट्टू', 'description': 'Steamed rice cake with chickpea curry', 'cuisine_type': 'south_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 350, 'calories': 380, 'protein_g': 14, 'carbs_g': 65, 'fats_g': 10, 'fiber_g': 10, 'prep_time_minutes': 15, 'cook_time_minutes': 25, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 84, 'ingredients': [{'name': 'rice_flour', 'quantity': 120, 'unit': 'g'}, {'name': 'coconut', 'quantity': 40, 'unit': 'g'}, {'name': 'chickpeas', 'quantity': 80, 'unit': 'g'}, {'name': 'onion', 'quantity': 40, 'unit': 'g'}, {'name': 'coconut_oil', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Medu Vada', 'name_hindi': 'मेदु वड़ा', 'description': 'Crispy lentil donuts', 'cuisine_type': 'south_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 200, 'calories': 320, 'protein_g': 12, 'carbs_g': 38, 'fats_g': 14, 'fiber_g': 6, 'prep_time_minutes': 120, 'cook_time_minutes': 20, 'difficulty_level': 'hard', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 89, 'ingredients': [{'name': 'urad_dal', 'quantity': 100, 'unit': 'g'}, {'name': 'green_chili', 'quantity': 5, 'unit': 'g'}, {'name': 'ginger', 'quantity': 5, 'unit': 'g'}, {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'}, {'name': 'oil', 'quantity': 20, 'unit': 'ml'}]},
    {'name': 'Aloo Puri', 'name_hindi': 'आलू पूरी', 'description': 'Fried bread with potato curry', 'cuisine_type': 'north_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 350, 'calories': 480, 'protein_g': 12, 'carbs_g': 68, 'fats_g': 18, 'fiber_g': 6, 'prep_time_minutes': 15, 'cook_time_minutes': 25, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['wheat'], 'popularity_score': 91, 'ingredients': [{'name': 'whole_wheat_flour', 'quantity': 100, 'unit': 'g'}, {'name': 'potato', 'quantity': 150, 'unit': 'g'}, {'name': 'tomato', 'quantity': 50, 'unit': 'g'}, {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'turmeric', 'quantity': 1, 'unit': 'g'}, {'name': 'oil', 'quantity': 25, 'unit': 'ml'}]},
    {'name': 'Kanda Poha', 'name_hindi': 'कांदा पोहा', 'description': 'Onion flattened rice', 'cuisine_type': 'north_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 240, 'calories': 300, 'protein_g': 7, 'carbs_g': 50, 'fats_g': 9, 'fiber_g': 4, 'prep_time_minutes': 10, 'cook_time_minutes': 10, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 86, 'ingredients': [{'name': 'poha', 'quantity': 100, 'unit': 'g'}, {'name': 'onion', 'quantity': 60, 'unit': 'g'}, {'name': 'potato', 'quantity': 40, 'unit': 'g'}, {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'turmeric', 'quantity': 1, 'unit': 'g'}, {'name': 'oil', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Chia Pudding', 'name_hindi': 'चिया पुडिंग', 'description': 'Overnight chia seed pudding', 'cuisine_type': 'continental', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 250, 'calories': 280, 'protein_g': 10, 'carbs_g': 38, 'fats_g': 10, 'fiber_g': 12, 'prep_time_minutes': 480, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 83, 'ingredients': [{'name': 'chia_seeds', 'quantity': 40, 'unit': 'g'}, {'name': 'milk', 'quantity': 200, 'unit': 'ml'}, {'name': 'honey', 'quantity': 15, 'unit': 'ml'}, {'name': 'mixed_berries', 'quantity': 50, 'unit': 'g'}]},
    {'name': 'Ragi Dosa', 'name_hindi': 'रागी डोसा', 'description': 'Finger millet crepe', 'cuisine_type': 'south_indian', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 280, 'calories': 310, 'protein_g': 10, 'carbs_g': 54, 'fats_g': 8, 'fiber_g': 6, 'prep_time_minutes': 120, 'cook_time_minutes': 15, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 81, 'ingredients': [{'name': 'ragi_flour', 'quantity': 100, 'unit': 'g'}, {'name': 'rice_flour', 'quantity': 50, 'unit': 'g'}, {'name': 'onion', 'quantity': 30, 'unit': 'g'}, {'name': 'green_chili', 'quantity': 5, 'unit': 'g'}, {'name': 'oil', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Quinoa Breakfast Bowl', 'name_hindi': 'क्विनोआ बाउल', 'description': 'Protein-rich quinoa with fruits', 'cuisine_type': 'continental', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 320, 'calories': 360, 'protein_g': 14, 'carbs_g': 58, 'fats_g': 10, 'fiber_g': 8, 'prep_time_minutes': 10, 'cook_time_minutes': 20, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': False, 'contains_allergens': ['dairy', 'tree_nuts'], 'popularity_score': 84, 'ingredients': [{'name': 'quinoa', 'quantity': 80, 'unit': 'g'}, {'name': 'milk', 'quantity': 150, 'unit': 'ml'}, {'name': 'banana', 'quantity': 1, 'unit': 'piece'}, {'name': 'almonds', 'quantity': 15, 'unit': 'g'}, {'name': 'honey', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Avocado Toast', 'name_hindi': 'एवोकाडो टोस्ट', 'description': 'Healthy fats with whole grain', 'cuisine_type': 'continental', 'meal_type': 'breakfast', 'dish_category': 'main_course', 'serving_size_g': 220, 'calories': 340, 'protein_g': 12, 'carbs_g': 38, 'fats_g': 16, 'fiber_g': 10, 'prep_time_minutes': 5, 'cook_time_minutes': 3, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['wheat'], 'popularity_score': 88, 'ingredients': [{'name': 'whole_wheat_bread', 'quantity': 2, 'unit': 'slice'}, {'name': 'avocado', 'quantity': 100, 'unit': 'g'}, {'name': 'cherry_tomatoes', 'quantity': 40, 'unit': 'g'}, {'name': 'lemon_juice', 'quantity': 10, 'unit': 'ml'}, {'name': 'salt', 'quantity': 2, 'unit': 'g'}]},
]

# Lunch Dishes (50+ dishes)
LUNCH_DISHES = [
    {
        'name': 'Grilled Chicken Breast with Brown Rice',
        'name_hindi': 'ग्रिल्ड चिकन',
        'description': 'Lean protein with complex carbs',
        'cuisine_type': 'continental',
        'meal_type': 'lunch',
        'dish_category': 'main_course',
        'serving_size_g': 400,
        'calories': 520,
        'protein_g': 45,
        'carbs_g': 55,
        'fats_g': 12,
        'fiber_g': 4,
        'prep_time_minutes': 10,
        'cook_time_minutes': 25,
        'difficulty_level': 'easy',
        'is_vegetarian': False,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 95,
        'ingredients': [
            {'name': 'chicken_breast', 'quantity': 200, 'unit': 'g'},
            {'name': 'brown_rice', 'quantity': 100, 'unit': 'g'},
            {'name': 'broccoli', 'quantity': 80, 'unit': 'g'},
            {'name': 'olive_oil', 'quantity': 10, 'unit': 'ml'},
            {'name': 'garlic', 'quantity': 5, 'unit': 'g'},
            {'name': 'lemon_juice', 'quantity': 10, 'unit': 'ml'},
            {'name': 'salt', 'quantity': 3, 'unit': 'g'},
            {'name': 'black_pepper', 'quantity': 2, 'unit': 'g'},
        ]
    },
    {
        'name': 'Dal Tadka with Roti',
        'name_hindi': 'दाल तड़का',
        'description': 'Tempered lentils with flatbread',
        'cuisine_type': 'north_indian',
        'meal_type': 'lunch',
        'dish_category': 'main_course',
        'serving_size_g': 450,
        'calories': 480,
        'protein_g': 22,
        'carbs_g': 72,
        'fats_g': 12,
        'fiber_g': 12,
        'prep_time_minutes': 15,
        'cook_time_minutes': 30,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': False,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': ['wheat'],
        'popularity_score': 92,
        'ingredients': [
            {'name': 'toor_dal', 'quantity': 100, 'unit': 'g'},
            {'name': 'whole_wheat_flour', 'quantity': 100, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 60, 'unit': 'g'},
            {'name': 'onion', 'quantity': 40, 'unit': 'g'},
            {'name': 'garlic', 'quantity': 10, 'unit': 'g'},
            {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'},
            {'name': 'turmeric', 'quantity': 1, 'unit': 'g'},
            {'name': 'ghee', 'quantity': 10, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Rajma Chawal',
        'name_hindi': 'राजमा चावल',
        'description': 'Kidney beans curry with rice',
        'cuisine_type': 'north_indian',
        'meal_type': 'lunch',
        'dish_category': 'main_course',
        'serving_size_g': 500,
        'calories': 550,
        'protein_g': 24,
        'carbs_g': 85,
        'fats_g': 14,
        'fiber_g': 15,
        'prep_time_minutes': 20,
        'cook_time_minutes': 40,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 94,
        'ingredients': [
            {'name': 'rajma', 'quantity': 100, 'unit': 'g'},
            {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 80, 'unit': 'g'},
            {'name': 'onion', 'quantity': 60, 'unit': 'g'},
            {'name': 'ginger_garlic_paste', 'quantity': 10, 'unit': 'g'},
            {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'},
            {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'},
            {'name': 'oil', 'quantity': 15, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Chole Bhature',
        'name_hindi': 'छोले भटूरे',
        'description': 'Spiced chickpeas with fried bread',
        'cuisine_type': 'north_indian',
        'meal_type': 'lunch',
        'dish_category': 'main_course',
        'serving_size_g': 450,
        'calories': 620,
        'protein_g': 20,
        'carbs_g': 78,
        'fats_g': 26,
        'fiber_g': 12,
        'prep_time_minutes': 20,
        'cook_time_minutes': 35,
        'difficulty_level': 'hard',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': False,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': ['wheat'],
        'popularity_score': 90,
        'ingredients': [
            {'name': 'chickpeas', 'quantity': 150, 'unit': 'g'},
            {'name': 'all_purpose_flour', 'quantity': 100, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 60, 'unit': 'g'},
            {'name': 'onion', 'quantity': 50, 'unit': 'g'},
            {'name': 'tea_bags', 'quantity': 1, 'unit': 'piece'},
            {'name': 'chole_masala', 'quantity': 5, 'unit': 'g'},
            {'name': 'oil', 'quantity': 30, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Paneer Tikka Masala with Naan',
        'name_hindi': 'पनीर टिक्का मसाला',
        'description': 'Cottage cheese in creamy tomato gravy',
        'cuisine_type': 'north_indian',
        'meal_type': 'lunch',
        'dish_category': 'main_course',
        'serving_size_g': 480,
        'calories': 580,
        'protein_g': 28,
        'carbs_g': 62,
        'fats_g': 24,
        'fiber_g': 6,
        'prep_time_minutes': 20,
        'cook_time_minutes': 30,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': False,
        'is_dairy_free': False,
        'is_nut_free': False,
        'contains_allergens': ['wheat', 'dairy', 'tree_nuts'],
        'popularity_score': 96,
        'ingredients': [
            {'name': 'paneer', 'quantity': 200, 'unit': 'g'},
            {'name': 'all_purpose_flour', 'quantity': 100, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 100, 'unit': 'g'},
            {'name': 'cream', 'quantity': 50, 'unit': 'ml'},
            {'name': 'cashews', 'quantity': 20, 'unit': 'g'},
            {'name': 'ginger_garlic_paste', 'quantity': 15, 'unit': 'g'},
            {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'},
            {'name': 'butter', 'quantity': 20, 'unit': 'g'},
        ]
    },
    {
        'name': 'Fish Curry with Rice',
        'name_hindi': 'मछली करी',
        'description': 'Bengali style fish curry',
        'cuisine_type': 'north_indian',
        'meal_type': 'lunch',
        'dish_category': 'main_course',
        'serving_size_g': 450,
        'calories': 510,
        'protein_g': 38,
        'carbs_g': 58,
        'fats_g': 14,
        'fiber_g': 3,
        'prep_time_minutes': 15,
        'cook_time_minutes': 25,
        'difficulty_level': 'medium',
        'is_vegetarian': False,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': ['fish'],
        'popularity_score': 88,
        'ingredients': [
            {'name': 'fish', 'quantity': 200, 'unit': 'g'},
            {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 60, 'unit': 'g'},
            {'name': 'onion', 'quantity': 50, 'unit': 'g'},
            {'name': 'mustard_oil', 'quantity': 15, 'unit': 'ml'},
            {'name': 'turmeric', 'quantity': 2, 'unit': 'g'},
            {'name': 'red_chili_powder', 'quantity': 3, 'unit': 'g'},
        ]
    },
    {
        'name': 'Vegetable Biryani',
        'name_hindi': 'वेज बिरयानी',
        'description': 'Aromatic rice with mixed vegetables',
        'cuisine_type': 'north_indian',
        'meal_type': 'lunch',
        'dish_category': 'main_course',
        'serving_size_g': 500,
        'calories': 540,
        'protein_g': 14,
        'carbs_g': 88,
        'fats_g': 16,
        'fiber_g': 8,
        'prep_time_minutes': 25,
        'cook_time_minutes': 35,
        'difficulty_level': 'hard',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': False,
        'contains_allergens': ['tree_nuts'],
        'popularity_score': 93,
        'ingredients': [
            {'name': 'basmati_rice', 'quantity': 150, 'unit': 'g'},
            {'name': 'mixed_vegetables', 'quantity': 150, 'unit': 'g'},
            {'name': 'onion', 'quantity': 60, 'unit': 'g'},
            {'name': 'curd', 'quantity': 50, 'unit': 'g'},
            {'name': 'cashews', 'quantity': 15, 'unit': 'g'},
            {'name': 'biryani_masala', 'quantity': 5, 'unit': 'g'},
            {'name': 'ghee', 'quantity': 20, 'unit': 'ml'},
        ]
    },
    # Additional 40+ lunch dishes to reach 50+ total
    {'name': 'Kadhi Pakora', 'name_hindi': 'कढ़ी पकोड़ा', 'description': 'Yogurt curry with fritters', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 450, 'calories': 420, 'protein_g': 16, 'carbs_g': 58, 'fats_g': 14, 'fiber_g': 6, 'prep_time_minutes': 20, 'cook_time_minutes': 30, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 88, 'ingredients': [{'name': 'curd', 'quantity': 200, 'unit': 'g'}, {'name': 'besan', 'quantity': 80, 'unit': 'g'}, {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'}, {'name': 'onion', 'quantity': 40, 'unit': 'g'}, {'name': 'turmeric', 'quantity': 2, 'unit': 'g'}, {'name': 'oil', 'quantity': 18, 'unit': 'ml'}]},
    {'name': 'Baingan Bharta with Roti', 'name_hindi': 'बैंगन भर्ता', 'description': 'Roasted eggplant mash', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 420, 'calories': 390, 'protein_g': 12, 'carbs_g': 56, 'fats_g': 14, 'fiber_g': 10, 'prep_time_minutes': 15, 'cook_time_minutes': 25, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['wheat'], 'popularity_score': 85, 'ingredients': [{'name': 'eggplant', 'quantity': 200, 'unit': 'g'}, {'name': 'whole_wheat_flour', 'quantity': 100, 'unit': 'g'}, {'name': 'tomato', 'quantity': 60, 'unit': 'g'}, {'name': 'onion', 'quantity': 50, 'unit': 'g'}, {'name': 'ginger_garlic_paste', 'quantity': 10, 'unit': 'g'}, {'name': 'oil', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Aloo Gobi', 'name_hindi': 'आलू गोभी', 'description': 'Potato and cauliflower curry', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 400, 'calories': 360, 'protein_g': 10, 'carbs_g': 58, 'fats_g': 12, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 20, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 87, 'ingredients': [{'name': 'potato', 'quantity': 150, 'unit': 'g'}, {'name': 'cauliflower', 'quantity': 150, 'unit': 'g'}, {'name': 'tomato', 'quantity': 50, 'unit': 'g'}, {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'turmeric', 'quantity': 1, 'unit': 'g'}, {'name': 'oil', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Bhindi Masala', 'name_hindi': 'भिंडी मसाला', 'description': 'Spiced okra curry', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 380, 'calories': 340, 'protein_g': 8, 'carbs_g': 48, 'fats_g': 14, 'fiber_g': 8, 'prep_time_minutes': 10, 'cook_time_minutes': 20, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 84, 'ingredients': [{'name': 'okra', 'quantity': 200, 'unit': 'g'}, {'name': 'onion', 'quantity': 60, 'unit': 'g'}, {'name': 'tomato', 'quantity': 50, 'unit': 'g'}, {'name': 'cumin_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'coriander_powder', 'quantity': 3, 'unit': 'g'}, {'name': 'oil', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Matar Paneer', 'name_hindi': 'मटर पनीर', 'description': 'Peas and cottage cheese curry', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 450, 'calories': 480, 'protein_g': 22, 'carbs_g': 52, 'fats_g': 20, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 25, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 92, 'ingredients': [{'name': 'paneer', 'quantity': 150, 'unit': 'g'}, {'name': 'peas', 'quantity': 100, 'unit': 'g'}, {'name': 'tomato', 'quantity': 80, 'unit': 'g'}, {'name': 'onion', 'quantity': 50, 'unit': 'g'}, {'name': 'cream', 'quantity': 30, 'unit': 'ml'}, {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'}, {'name': 'oil', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Chicken Biryani', 'name_hindi': 'चिकन बिरयानी', 'description': 'Aromatic rice with chicken', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 550, 'calories': 640, 'protein_g': 38, 'carbs_g': 78, 'fats_g': 20, 'fiber_g': 4, 'prep_time_minutes': 30, 'cook_time_minutes': 45, 'difficulty_level': 'hard', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': False, 'contains_allergens': ['dairy', 'tree_nuts'], 'popularity_score': 98, 'ingredients': [{'name': 'chicken', 'quantity': 250, 'unit': 'g'}, {'name': 'basmati_rice', 'quantity': 150, 'unit': 'g'}, {'name': 'curd', 'quantity': 60, 'unit': 'g'}, {'name': 'onion', 'quantity': 80, 'unit': 'g'}, {'name': 'biryani_masala', 'quantity': 6, 'unit': 'g'}, {'name': 'ghee', 'quantity': 25, 'unit': 'ml'}]},
    {'name': 'Mutton Rogan Josh', 'name_hindi': 'मटन रोगन जोश', 'description': 'Kashmiri mutton curry', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 480, 'calories': 580, 'protein_g': 36, 'carbs_g': 48, 'fats_g': 26, 'fiber_g': 4, 'prep_time_minutes': 20, 'cook_time_minutes': 60, 'difficulty_level': 'hard', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 90, 'ingredients': [{'name': 'mutton', 'quantity': 250, 'unit': 'g'}, {'name': 'curd', 'quantity': 80, 'unit': 'g'}, {'name': 'onion', 'quantity': 70, 'unit': 'g'}, {'name': 'tomato', 'quantity': 60, 'unit': 'g'}, {'name': 'kashmiri_chili', 'quantity': 4, 'unit': 'g'}, {'name': 'ghee', 'quantity': 20, 'unit': 'ml'}]},
    {'name': 'Sambar Rice', 'name_hindi': 'सांभर चावल', 'description': 'Lentil stew with rice', 'cuisine_type': 'south_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 480, 'calories': 420, 'protein_g': 16, 'carbs_g': 72, 'fats_g': 8, 'fiber_g': 10, 'prep_time_minutes': 15, 'cook_time_minutes': 30, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 89, 'ingredients': [{'name': 'toor_dal', 'quantity': 80, 'unit': 'g'}, {'name': 'basmati_rice', 'quantity': 120, 'unit': 'g'}, {'name': 'mixed_vegetables', 'quantity': 100, 'unit': 'g'}, {'name': 'tamarind', 'quantity': 15, 'unit': 'g'}, {'name': 'sambar_powder', 'quantity': 5, 'unit': 'g'}, {'name': 'oil', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Curd Rice', 'name_hindi': 'दही चावल', 'description': 'Yogurt rice with tempering', 'cuisine_type': 'south_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 400, 'calories': 380, 'protein_g': 12, 'carbs_g': 68, 'fats_g': 8, 'fiber_g': 2, 'prep_time_minutes': 10, 'cook_time_minutes': 15, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 86, 'ingredients': [{'name': 'basmati_rice', 'quantity': 120, 'unit': 'g'}, {'name': 'curd', 'quantity': 150, 'unit': 'g'}, {'name': 'cucumber', 'quantity': 40, 'unit': 'g'}, {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'}, {'name': 'oil', 'quantity': 8, 'unit': 'ml'}]},
    {'name': 'Lemon Rice', 'name_hindi': 'नींबू चावल', 'description': 'Tangy lemon flavored rice', 'cuisine_type': 'south_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 350, 'calories': 380, 'protein_g': 8, 'carbs_g': 72, 'fats_g': 10, 'fiber_g': 3, 'prep_time_minutes': 10, 'cook_time_minutes': 15, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': ['tree_nuts'], 'popularity_score': 85, 'ingredients': [{'name': 'basmati_rice', 'quantity': 150, 'unit': 'g'}, {'name': 'lemon_juice', 'quantity': 30, 'unit': 'ml'}, {'name': 'peanuts', 'quantity': 20, 'unit': 'g'}, {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'turmeric', 'quantity': 1, 'unit': 'g'}, {'name': 'oil', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Chicken Tikka Wrap', 'name_hindi': 'चिकन टिक्का रैप', 'description': 'Grilled chicken in wrap', 'cuisine_type': 'fusion', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 350, 'calories': 480, 'protein_g': 38, 'carbs_g': 52, 'fats_g': 14, 'fiber_g': 5, 'prep_time_minutes': 20, 'cook_time_minutes': 20, 'difficulty_level': 'medium', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': False, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['wheat', 'dairy'], 'popularity_score': 91, 'ingredients': [{'name': 'chicken', 'quantity': 180, 'unit': 'g'}, {'name': 'tortilla', 'quantity': 2, 'unit': 'piece'}, {'name': 'lettuce', 'quantity': 40, 'unit': 'g'}, {'name': 'curd', 'quantity': 30, 'unit': 'g'}, {'name': 'tandoori_masala', 'quantity': 5, 'unit': 'g'}]},
    {'name': 'Soya Chunks Curry', 'name_hindi': 'सोया करी', 'description': 'High protein soya curry', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 420, 'calories': 440, 'protein_g': 32, 'carbs_g': 58, 'fats_g': 12, 'fiber_g': 8, 'prep_time_minutes': 20, 'cook_time_minutes': 25, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['soy'], 'popularity_score': 83, 'ingredients': [{'name': 'soya_chunks', 'quantity': 100, 'unit': 'g'}, {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'}, {'name': 'tomato', 'quantity': 80, 'unit': 'g'}, {'name': 'onion', 'quantity': 60, 'unit': 'g'}, {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'}, {'name': 'oil', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Tuna Salad Bowl', 'name_hindi': 'टूना सलाद', 'description': 'Protein-rich tuna salad', 'cuisine_type': 'continental', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 380, 'calories': 420, 'protein_g': 40, 'carbs_g': 32, 'fats_g': 16, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['fish'], 'popularity_score': 87, 'ingredients': [{'name': 'tuna', 'quantity': 150, 'unit': 'g'}, {'name': 'mixed_greens', 'quantity': 100, 'unit': 'g'}, {'name': 'quinoa', 'quantity': 60, 'unit': 'g'}, {'name': 'cherry_tomatoes', 'quantity': 50, 'unit': 'g'}, {'name': 'olive_oil', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Moong Dal Khichdi', 'name_hindi': 'मूंग दाल खिचड़ी', 'description': 'Comfort food rice and lentils', 'cuisine_type': 'north_indian', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 450, 'calories': 390, 'protein_g': 16, 'carbs_g': 68, 'fats_g': 8, 'fiber_g': 10, 'prep_time_minutes': 10, 'cook_time_minutes': 25, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 86, 'ingredients': [{'name': 'rice', 'quantity': 100, 'unit': 'g'}, {'name': 'moong_dal', 'quantity': 80, 'unit': 'g'}, {'name': 'mixed_vegetables', 'quantity': 80, 'unit': 'g'}, {'name': 'turmeric', 'quantity': 1, 'unit': 'g'}, {'name': 'ghee', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Grilled Paneer Salad', 'name_hindi': 'ग्रिल्ड पनीर सलाद', 'description': 'High protein vegetarian salad', 'cuisine_type': 'fusion', 'meal_type': 'lunch', 'dish_category': 'main_course', 'serving_size_g': 380, 'calories': 420, 'protein_g': 26, 'carbs_g': 32, 'fats_g': 20, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 10, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 87, 'ingredients': [{'name': 'paneer', 'quantity': 150, 'unit': 'g'}, {'name': 'mixed_greens', 'quantity': 100, 'unit': 'g'}, {'name': 'cherry_tomatoes', 'quantity': 50, 'unit': 'g'}, {'name': 'cucumber', 'quantity': 50, 'unit': 'g'}, {'name': 'olive_oil', 'quantity': 15, 'unit': 'ml'}, {'name': 'lemon_juice', 'quantity': 15, 'unit': 'ml'}]},
]

# Dinner Dishes (50+ dishes)
DINNER_DISHES = [
    {
        'name': 'Grilled Salmon with Quinoa',
        'name_hindi': 'ग्रिल्ड सैल्मन',
        'description': 'Omega-3 rich fish with protein-packed quinoa',
        'cuisine_type': 'continental',
        'meal_type': 'dinner',
        'dish_category': 'main_course',
        'serving_size_g': 400,
        'calories': 520,
        'protein_g': 42,
        'carbs_g': 45,
        'fats_g': 18,
        'fiber_g': 6,
        'prep_time_minutes': 10,
        'cook_time_minutes': 20,
        'difficulty_level': 'medium',
        'is_vegetarian': False,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': ['fish'],
        'popularity_score': 91,
        'ingredients': [
            {'name': 'salmon', 'quantity': 200, 'unit': 'g'},
            {'name': 'quinoa', 'quantity': 80, 'unit': 'g'},
            {'name': 'asparagus', 'quantity': 100, 'unit': 'g'},
            {'name': 'olive_oil', 'quantity': 12, 'unit': 'ml'},
            {'name': 'lemon_juice', 'quantity': 15, 'unit': 'ml'},
            {'name': 'garlic', 'quantity': 8, 'unit': 'g'},
            {'name': 'dill', 'quantity': 5, 'unit': 'g'},
        ]
    },
    {
        'name': 'Palak Paneer with Roti',
        'name_hindi': 'पालक पनीर',
        'description': 'Spinach and cottage cheese curry',
        'cuisine_type': 'north_indian',
        'meal_type': 'dinner',
        'dish_category': 'main_course',
        'serving_size_g': 450,
        'calories': 480,
        'protein_g': 24,
        'carbs_g': 52,
        'fats_g': 20,
        'fiber_g': 8,
        'prep_time_minutes': 15,
        'cook_time_minutes': 25,
        'difficulty_level': 'medium',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': False,
        'is_dairy_free': False,
        'is_nut_free': True,
        'contains_allergens': ['wheat', 'dairy'],
        'popularity_score': 94,
        'ingredients': [
            {'name': 'paneer', 'quantity': 150, 'unit': 'g'},
            {'name': 'spinach', 'quantity': 200, 'unit': 'g'},
            {'name': 'whole_wheat_flour', 'quantity': 100, 'unit': 'g'},
            {'name': 'onion', 'quantity': 50, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 40, 'unit': 'g'},
            {'name': 'cream', 'quantity': 30, 'unit': 'ml'},
            {'name': 'ginger_garlic_paste', 'quantity': 10, 'unit': 'g'},
            {'name': 'ghee', 'quantity': 15, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Chicken Curry with Rice',
        'name_hindi': 'चिकन करी',
        'description': 'Traditional chicken curry',
        'cuisine_type': 'north_indian',
        'meal_type': 'dinner',
        'dish_category': 'main_course',
        'serving_size_g': 480,
        'calories': 560,
        'protein_g': 42,
        'carbs_g': 62,
        'fats_g': 16,
        'fiber_g': 4,
        'prep_time_minutes': 15,
        'cook_time_minutes': 35,
        'difficulty_level': 'medium',
        'is_vegetarian': False,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 96,
        'ingredients': [
            {'name': 'chicken', 'quantity': 200, 'unit': 'g'},
            {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 80, 'unit': 'g'},
            {'name': 'onion', 'quantity': 60, 'unit': 'g'},
            {'name': 'curd', 'quantity': 50, 'unit': 'g'},
            {'name': 'ginger_garlic_paste', 'quantity': 15, 'unit': 'g'},
            {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'},
            {'name': 'oil', 'quantity': 18, 'unit': 'ml'},
        ]
    },
    {
        'name': 'Mixed Dal with Jeera Rice',
        'name_hindi': 'मिक्स दाल',
        'description': 'Five lentil mix with cumin rice',
        'cuisine_type': 'north_indian',
        'meal_type': 'dinner',
        'dish_category': 'main_course',
        'serving_size_g': 450,
        'calories': 460,
        'protein_g': 20,
        'carbs_g': 75,
        'fats_g': 10,
        'fiber_g': 14,
        'prep_time_minutes': 15,
        'cook_time_minutes': 30,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 89,
        'ingredients': [
            {'name': 'mixed_dal', 'quantity': 100, 'unit': 'g'},
            {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'},
            {'name': 'tomato', 'quantity': 50, 'unit': 'g'},
            {'name': 'onion', 'quantity': 40, 'unit': 'g'},
            {'name': 'cumin_seeds', 'quantity': 3, 'unit': 'g'},
            {'name': 'turmeric', 'quantity': 1, 'unit': 'g'},
            {'name': 'ghee', 'quantity': 12, 'unit': 'ml'},
        ]
    },
    # Additional 40+ dinner dishes to reach 50+ total
    {'name': 'Butter Chicken', 'name_hindi': 'बटर चिकन', 'description': 'Creamy tomato chicken curry', 'cuisine_type': 'north_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 480, 'calories': 580, 'protein_g': 40, 'carbs_g': 48, 'fats_g': 24, 'fiber_g': 4, 'prep_time_minutes': 20, 'cook_time_minutes': 35, 'difficulty_level': 'medium', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': False, 'contains_allergens': ['dairy', 'tree_nuts'], 'popularity_score': 97, 'ingredients': [{'name': 'chicken', 'quantity': 250, 'unit': 'g'}, {'name': 'tomato', 'quantity': 100, 'unit': 'g'}, {'name': 'cream', 'quantity': 60, 'unit': 'ml'}, {'name': 'butter', 'quantity': 30, 'unit': 'g'}, {'name': 'cashews', 'quantity': 20, 'unit': 'g'}, {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'}]},
    {'name': 'Tandoori Chicken with Naan', 'name_hindi': 'तंदूरी चिकन', 'description': 'Grilled marinated chicken', 'cuisine_type': 'north_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 450, 'calories': 520, 'protein_g': 45, 'carbs_g': 52, 'fats_g': 14, 'fiber_g': 4, 'prep_time_minutes': 120, 'cook_time_minutes': 25, 'difficulty_level': 'medium', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': False, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['wheat', 'dairy'], 'popularity_score': 95, 'ingredients': [{'name': 'chicken', 'quantity': 250, 'unit': 'g'}, {'name': 'curd', 'quantity': 80, 'unit': 'g'}, {'name': 'all_purpose_flour', 'quantity': 100, 'unit': 'g'}, {'name': 'tandoori_masala', 'quantity': 10, 'unit': 'g'}, {'name': 'lemon_juice', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Egg Curry with Rice', 'name_hindi': 'अंडा करी', 'description': 'Boiled eggs in spicy gravy', 'cuisine_type': 'north_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 450, 'calories': 480, 'protein_g': 24, 'carbs_g': 62, 'fats_g': 16, 'fiber_g': 4, 'prep_time_minutes': 15, 'cook_time_minutes': 25, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['eggs'], 'popularity_score': 88, 'ingredients': [{'name': 'eggs', 'quantity': 4, 'unit': 'piece'}, {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'}, {'name': 'tomato', 'quantity': 80, 'unit': 'g'}, {'name': 'onion', 'quantity': 60, 'unit': 'g'}, {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'}, {'name': 'oil', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Prawn Curry', 'name_hindi': 'झींगा करी', 'description': 'Coastal style prawn curry', 'cuisine_type': 'south_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 420, 'calories': 460, 'protein_g': 38, 'carbs_g': 48, 'fats_g': 14, 'fiber_g': 4, 'prep_time_minutes': 15, 'cook_time_minutes': 20, 'difficulty_level': 'medium', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['shellfish'], 'popularity_score': 89, 'ingredients': [{'name': 'prawns', 'quantity': 200, 'unit': 'g'}, {'name': 'coconut_milk', 'quantity': 100, 'unit': 'ml'}, {'name': 'tomato', 'quantity': 60, 'unit': 'g'}, {'name': 'curry_leaves', 'quantity': 5, 'unit': 'g'}, {'name': 'coconut_oil', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Mushroom Masala', 'name_hindi': 'मशरूम मसाला', 'description': 'Spiced mushroom curry', 'cuisine_type': 'north_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 400, 'calories': 360, 'protein_g': 14, 'carbs_g': 48, 'fats_g': 14, 'fiber_g': 6, 'prep_time_minutes': 15, 'cook_time_minutes': 20, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 84, 'ingredients': [{'name': 'mushrooms', 'quantity': 200, 'unit': 'g'}, {'name': 'tomato', 'quantity': 80, 'unit': 'g'}, {'name': 'onion', 'quantity': 60, 'unit': 'g'}, {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'}, {'name': 'oil', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Tofu Stir Fry with Quinoa', 'name_hindi': 'टोफू स्टिर फ्राई', 'description': 'Asian style tofu with quinoa', 'cuisine_type': 'fusion', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 400, 'calories': 420, 'protein_g': 24, 'carbs_g': 52, 'fats_g': 14, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 20, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['soy'], 'popularity_score': 86, 'ingredients': [{'name': 'tofu', 'quantity': 200, 'unit': 'g'}, {'name': 'quinoa', 'quantity': 80, 'unit': 'g'}, {'name': 'mixed_vegetables', 'quantity': 100, 'unit': 'g'}, {'name': 'soy_sauce', 'quantity': 15, 'unit': 'ml'}, {'name': 'sesame_oil', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Keema Pav', 'name_hindi': 'कीमा पाव', 'description': 'Minced meat with bread rolls', 'cuisine_type': 'north_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 400, 'calories': 540, 'protein_g': 32, 'carbs_g': 58, 'fats_g': 20, 'fiber_g': 4, 'prep_time_minutes': 15, 'cook_time_minutes': 30, 'difficulty_level': 'medium', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['wheat'], 'popularity_score': 90, 'ingredients': [{'name': 'minced_meat', 'quantity': 200, 'unit': 'g'}, {'name': 'pav_bread', 'quantity': 4, 'unit': 'piece'}, {'name': 'onion', 'quantity': 60, 'unit': 'g'}, {'name': 'tomato', 'quantity': 50, 'unit': 'g'}, {'name': 'garam_masala', 'quantity': 3, 'unit': 'g'}, {'name': 'oil', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Vegetable Pulao', 'name_hindi': 'वेज पुलाव', 'description': 'Mildly spiced rice with vegetables', 'cuisine_type': 'north_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 450, 'calories': 420, 'protein_g': 10, 'carbs_g': 78, 'fats_g': 10, 'fiber_g': 6, 'prep_time_minutes': 15, 'cook_time_minutes': 25, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': ['tree_nuts'], 'popularity_score': 87, 'ingredients': [{'name': 'basmati_rice', 'quantity': 150, 'unit': 'g'}, {'name': 'mixed_vegetables', 'quantity': 120, 'unit': 'g'}, {'name': 'onion', 'quantity': 50, 'unit': 'g'}, {'name': 'cashews', 'quantity': 15, 'unit': 'g'}, {'name': 'ghee', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Khichdi with Kadhi', 'name_hindi': 'खिचड़ी कढ़ी', 'description': 'Comfort food rice and lentils', 'cuisine_type': 'north_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 480, 'calories': 400, 'protein_g': 16, 'carbs_g': 68, 'fats_g': 10, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 30, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 85, 'ingredients': [{'name': 'rice', 'quantity': 100, 'unit': 'g'}, {'name': 'moong_dal', 'quantity': 60, 'unit': 'g'}, {'name': 'curd', 'quantity': 100, 'unit': 'g'}, {'name': 'besan', 'quantity': 40, 'unit': 'g'}, {'name': 'turmeric', 'quantity': 1, 'unit': 'g'}, {'name': 'ghee', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Grilled Chicken Salad', 'name_hindi': 'ग्रिल्ड चिकन सलाद', 'description': 'Protein-rich salad', 'cuisine_type': 'continental', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 380, 'calories': 380, 'protein_g': 42, 'carbs_g': 28, 'fats_g': 12, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 15, 'difficulty_level': 'easy', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 90, 'ingredients': [{'name': 'chicken_breast', 'quantity': 200, 'unit': 'g'}, {'name': 'mixed_greens', 'quantity': 100, 'unit': 'g'}, {'name': 'cherry_tomatoes', 'quantity': 50, 'unit': 'g'}, {'name': 'cucumber', 'quantity': 50, 'unit': 'g'}, {'name': 'olive_oil', 'quantity': 10, 'unit': 'ml'}, {'name': 'lemon_juice', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Shrimp Fried Rice', 'name_hindi': 'झींगा फ्राइड राइस', 'description': 'Asian style fried rice', 'cuisine_type': 'fusion', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 450, 'calories': 490, 'protein_g': 32, 'carbs_g': 68, 'fats_g': 12, 'fiber_g': 4, 'prep_time_minutes': 15, 'cook_time_minutes': 15, 'difficulty_level': 'medium', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['shellfish', 'soy'], 'popularity_score': 88, 'ingredients': [{'name': 'prawns', 'quantity': 150, 'unit': 'g'}, {'name': 'basmati_rice', 'quantity': 150, 'unit': 'g'}, {'name': 'mixed_vegetables', 'quantity': 80, 'unit': 'g'}, {'name': 'soy_sauce', 'quantity': 15, 'unit': 'ml'}, {'name': 'oil', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Vegetable Stir Fry with Noodles', 'name_hindi': 'वेज नूडल्स', 'description': 'Asian style vegetable noodles', 'cuisine_type': 'fusion', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 420, 'calories': 440, 'protein_g': 14, 'carbs_g': 72, 'fats_g': 12, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 15, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['wheat', 'soy'], 'popularity_score': 87, 'ingredients': [{'name': 'noodles', 'quantity': 150, 'unit': 'g'}, {'name': 'mixed_vegetables', 'quantity': 150, 'unit': 'g'}, {'name': 'soy_sauce', 'quantity': 15, 'unit': 'ml'}, {'name': 'garlic', 'quantity': 10, 'unit': 'g'}, {'name': 'oil', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Lamb Curry with Rice', 'name_hindi': 'लैम्ब करी', 'description': 'Tender lamb in spicy gravy', 'cuisine_type': 'north_indian', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 480, 'calories': 590, 'protein_g': 38, 'carbs_g': 52, 'fats_g': 24, 'fiber_g': 4, 'prep_time_minutes': 20, 'cook_time_minutes': 50, 'difficulty_level': 'hard', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 89, 'ingredients': [{'name': 'lamb', 'quantity': 220, 'unit': 'g'}, {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'}, {'name': 'tomato', 'quantity': 80, 'unit': 'g'}, {'name': 'onion', 'quantity': 60, 'unit': 'g'}, {'name': 'garam_masala', 'quantity': 4, 'unit': 'g'}, {'name': 'oil', 'quantity': 18, 'unit': 'ml'}]},
    {'name': 'Grilled Turkey with Sweet Potato', 'name_hindi': 'ग्रिल्ड टर्की', 'description': 'Lean protein with complex carbs', 'cuisine_type': 'continental', 'meal_type': 'dinner', 'dish_category': 'main_course', 'serving_size_g': 420, 'calories': 480, 'protein_g': 44, 'carbs_g': 52, 'fats_g': 10, 'fiber_g': 8, 'prep_time_minutes': 15, 'cook_time_minutes': 30, 'difficulty_level': 'medium', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 86, 'ingredients': [{'name': 'turkey_breast', 'quantity': 200, 'unit': 'g'}, {'name': 'sweet_potato', 'quantity': 200, 'unit': 'g'}, {'name': 'broccoli', 'quantity': 80, 'unit': 'g'}, {'name': 'olive_oil', 'quantity': 10, 'unit': 'ml'}, {'name': 'garlic', 'quantity': 5, 'unit': 'g'}]},
]

# Snack Dishes (30+ dishes)
SNACK_DISHES = [
    {
        'name': 'Protein Smoothie Bowl',
        'name_hindi': 'प्रोटीन स्मूदी',
        'description': 'Thick smoothie with toppings',
        'cuisine_type': 'continental',
        'meal_type': 'snack',
        'dish_category': 'beverage',
        'serving_size_g': 350,
        'calories': 320,
        'protein_g': 25,
        'carbs_g': 42,
        'fats_g': 8,
        'fiber_g': 6,
        'prep_time_minutes': 10,
        'cook_time_minutes': 0,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': False,
        'is_nut_free': False,
        'contains_allergens': ['dairy', 'tree_nuts'],
        'popularity_score': 90,
        'ingredients': [
            {'name': 'protein_powder', 'quantity': 30, 'unit': 'g'},
            {'name': 'banana', 'quantity': 1, 'unit': 'piece'},
            {'name': 'milk', 'quantity': 200, 'unit': 'ml'},
            {'name': 'peanut_butter', 'quantity': 15, 'unit': 'g'},
            {'name': 'chia_seeds', 'quantity': 10, 'unit': 'g'},
        ]
    },
    {
        'name': 'Roasted Chickpeas',
        'name_hindi': 'भुने चने',
        'description': 'Crunchy roasted chickpeas',
        'cuisine_type': 'north_indian',
        'meal_type': 'snack',
        'dish_category': 'side_dish',
        'serving_size_g': 100,
        'calories': 180,
        'protein_g': 10,
        'carbs_g': 28,
        'fats_g': 4,
        'fiber_g': 8,
        'prep_time_minutes': 5,
        'cook_time_minutes': 30,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 85,
        'ingredients': [
            {'name': 'chickpeas', 'quantity': 100, 'unit': 'g'},
            {'name': 'olive_oil', 'quantity': 5, 'unit': 'ml'},
            {'name': 'chaat_masala', 'quantity': 2, 'unit': 'g'},
            {'name': 'salt', 'quantity': 1, 'unit': 'g'},
        ]
    },
    {
        'name': 'Fruit and Nut Mix',
        'name_hindi': 'ड्राई फ्रूट्स',
        'description': 'Mixed nuts and dried fruits',
        'cuisine_type': 'continental',
        'meal_type': 'snack',
        'dish_category': 'side_dish',
        'serving_size_g': 80,
        'calories': 240,
        'protein_g': 8,
        'carbs_g': 28,
        'fats_g': 12,
        'fiber_g': 4,
        'prep_time_minutes': 0,
        'cook_time_minutes': 0,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': False,
        'contains_allergens': ['tree_nuts'],
        'popularity_score': 88,
        'ingredients': [
            {'name': 'almonds', 'quantity': 20, 'unit': 'g'},
            {'name': 'cashews', 'quantity': 20, 'unit': 'g'},
            {'name': 'walnuts', 'quantity': 15, 'unit': 'g'},
            {'name': 'raisins', 'quantity': 25, 'unit': 'g'},
        ]
    },
    # Additional 25+ snack dishes to reach 30+ total
    {'name': 'Sprouts Salad', 'name_hindi': 'अंकुरित सलाद', 'description': 'Protein-rich sprouts', 'cuisine_type': 'north_indian', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 150, 'calories': 140, 'protein_g': 12, 'carbs_g': 22, 'fats_g': 2, 'fiber_g': 6, 'prep_time_minutes': 5, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 82, 'ingredients': [{'name': 'mixed_sprouts', 'quantity': 100, 'unit': 'g'}, {'name': 'onion', 'quantity': 20, 'unit': 'g'}, {'name': 'tomato', 'quantity': 20, 'unit': 'g'}, {'name': 'lemon_juice', 'quantity': 10, 'unit': 'ml'}, {'name': 'chaat_masala', 'quantity': 2, 'unit': 'g'}]},
    {'name': 'Boiled Eggs', 'name_hindi': 'उबले अंडे', 'description': 'Simple protein snack', 'cuisine_type': 'continental', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 100, 'calories': 155, 'protein_g': 13, 'carbs_g': 1, 'fats_g': 11, 'fiber_g': 0, 'prep_time_minutes': 2, 'cook_time_minutes': 10, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['eggs'], 'popularity_score': 90, 'ingredients': [{'name': 'eggs', 'quantity': 2, 'unit': 'piece'}, {'name': 'salt', 'quantity': 1, 'unit': 'g'}, {'name': 'black_pepper', 'quantity': 1, 'unit': 'g'}]},
    {'name': 'Paneer Tikka', 'name_hindi': 'पनीर टिक्का', 'description': 'Grilled cottage cheese cubes', 'cuisine_type': 'north_indian', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 150, 'calories': 280, 'protein_g': 18, 'carbs_g': 12, 'fats_g': 18, 'fiber_g': 2, 'prep_time_minutes': 30, 'cook_time_minutes': 15, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 92, 'ingredients': [{'name': 'paneer', 'quantity': 120, 'unit': 'g'}, {'name': 'curd', 'quantity': 40, 'unit': 'g'}, {'name': 'bell_pepper', 'quantity': 30, 'unit': 'g'}, {'name': 'tandoori_masala', 'quantity': 5, 'unit': 'g'}, {'name': 'oil', 'quantity': 8, 'unit': 'ml'}]},
    {'name': 'Makhana Roasted', 'name_hindi': 'भुना मखाना', 'description': 'Roasted fox nuts', 'cuisine_type': 'north_indian', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 50, 'calories': 180, 'protein_g': 5, 'carbs_g': 32, 'fats_g': 4, 'fiber_g': 3, 'prep_time_minutes': 5, 'cook_time_minutes': 10, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 84, 'ingredients': [{'name': 'makhana', 'quantity': 50, 'unit': 'g'}, {'name': 'ghee', 'quantity': 5, 'unit': 'ml'}, {'name': 'salt', 'quantity': 1, 'unit': 'g'}, {'name': 'black_pepper', 'quantity': 1, 'unit': 'g'}]},
    {'name': 'Hummus with Veggies', 'name_hindi': 'हम्मस', 'description': 'Chickpea dip with vegetables', 'cuisine_type': 'continental', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 180, 'calories': 220, 'protein_g': 10, 'carbs_g': 28, 'fats_g': 8, 'fiber_g': 8, 'prep_time_minutes': 10, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 86, 'ingredients': [{'name': 'chickpeas', 'quantity': 100, 'unit': 'g'}, {'name': 'tahini', 'quantity': 15, 'unit': 'g'}, {'name': 'carrot_sticks', 'quantity': 50, 'unit': 'g'}, {'name': 'cucumber_sticks', 'quantity': 50, 'unit': 'g'}, {'name': 'lemon_juice', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Dhokla', 'name_hindi': 'ढोकला', 'description': 'Steamed gram flour cake', 'cuisine_type': 'north_indian', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 150, 'calories': 200, 'protein_g': 8, 'carbs_g': 36, 'fats_g': 4, 'fiber_g': 4, 'prep_time_minutes': 15, 'cook_time_minutes': 20, 'difficulty_level': 'medium', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 87, 'ingredients': [{'name': 'besan', 'quantity': 100, 'unit': 'g'}, {'name': 'curd', 'quantity': 50, 'unit': 'g'}, {'name': 'mustard_seeds', 'quantity': 2, 'unit': 'g'}, {'name': 'green_chili', 'quantity': 5, 'unit': 'g'}, {'name': 'oil', 'quantity': 5, 'unit': 'ml'}]},
    {'name': 'Fruit Chaat', 'name_hindi': 'फ्रूट चाट', 'description': 'Spiced fruit salad', 'cuisine_type': 'north_indian', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 200, 'calories': 160, 'protein_g': 3, 'carbs_g': 38, 'fats_g': 1, 'fiber_g': 6, 'prep_time_minutes': 10, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 85, 'ingredients': [{'name': 'apple', 'quantity': 60, 'unit': 'g'}, {'name': 'banana', 'quantity': 60, 'unit': 'g'}, {'name': 'pomegranate', 'quantity': 40, 'unit': 'g'}, {'name': 'chaat_masala', 'quantity': 2, 'unit': 'g'}, {'name': 'lemon_juice', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Cottage Cheese with Berries', 'name_hindi': 'कॉटेज चीज़', 'description': 'Low-fat cheese with fruits', 'cuisine_type': 'continental', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 200, 'calories': 180, 'protein_g': 16, 'carbs_g': 22, 'fats_g': 4, 'fiber_g': 3, 'prep_time_minutes': 5, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 83, 'ingredients': [{'name': 'cottage_cheese', 'quantity': 150, 'unit': 'g'}, {'name': 'mixed_berries', 'quantity': 50, 'unit': 'g'}, {'name': 'honey', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Protein Balls', 'name_hindi': 'प्रोटीन बॉल्स', 'description': 'Energy balls with dates and nuts', 'cuisine_type': 'continental', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 80, 'calories': 220, 'protein_g': 8, 'carbs_g': 32, 'fats_g': 9, 'fiber_g': 5, 'prep_time_minutes': 15, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': ['tree_nuts'], 'popularity_score': 88, 'ingredients': [{'name': 'dates', 'quantity': 40, 'unit': 'g'}, {'name': 'almonds', 'quantity': 20, 'unit': 'g'}, {'name': 'protein_powder', 'quantity': 15, 'unit': 'g'}, {'name': 'cocoa_powder', 'quantity': 5, 'unit': 'g'}]},
    {'name': 'Cucumber Raita', 'name_hindi': 'खीरा रायता', 'description': 'Cooling yogurt side dish', 'cuisine_type': 'north_indian', 'meal_type': 'snack', 'dish_category': 'side_dish', 'serving_size_g': 150, 'calories': 90, 'protein_g': 6, 'carbs_g': 12, 'fats_g': 3, 'fiber_g': 2, 'prep_time_minutes': 10, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 82, 'ingredients': [{'name': 'curd', 'quantity': 120, 'unit': 'g'}, {'name': 'cucumber', 'quantity': 60, 'unit': 'g'}, {'name': 'cumin_powder', 'quantity': 1, 'unit': 'g'}, {'name': 'salt', 'quantity': 1, 'unit': 'g'}]},
]

# Pre-Workout Dishes (10+ dishes)
PRE_WORKOUT_DISHES = [
    {
        'name': 'Banana with Peanut Butter',
        'name_hindi': 'केला पीनट बटर',
        'description': 'Quick energy with healthy fats',
        'cuisine_type': 'continental',
        'meal_type': 'pre_workout',
        'dish_category': 'snack',
        'serving_size_g': 150,
        'calories': 250,
        'protein_g': 8,
        'carbs_g': 35,
        'fats_g': 10,
        'fiber_g': 4,
        'prep_time_minutes': 2,
        'cook_time_minutes': 0,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': False,
        'contains_allergens': ['peanuts'],
        'popularity_score': 92,
        'ingredients': [
            {'name': 'banana', 'quantity': 1, 'unit': 'piece'},
            {'name': 'peanut_butter', 'quantity': 20, 'unit': 'g'},
        ]
    },
    {
        'name': 'Oats Energy Bar',
        'name_hindi': 'ओट्स एनर्जी बार',
        'description': 'Homemade energy bar',
        'cuisine_type': 'continental',
        'meal_type': 'pre_workout',
        'dish_category': 'snack',
        'serving_size_g': 80,
        'calories': 200,
        'protein_g': 6,
        'carbs_g': 32,
        'fats_g': 6,
        'fiber_g': 4,
        'prep_time_minutes': 15,
        'cook_time_minutes': 20,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': True,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': False,
        'contains_allergens': ['tree_nuts'],
        'popularity_score': 87,
        'ingredients': [
            {'name': 'rolled_oats', 'quantity': 50, 'unit': 'g'},
            {'name': 'dates', 'quantity': 30, 'unit': 'g'},
            {'name': 'almonds', 'quantity': 15, 'unit': 'g'},
            {'name': 'honey', 'quantity': 10, 'unit': 'ml'},
        ]
    },
    # Additional 8+ pre-workout dishes to reach 10+ total
    {'name': 'Apple with Almond Butter', 'name_hindi': 'सेब बादाम बटर', 'description': 'Quick carbs with healthy fats', 'cuisine_type': 'continental', 'meal_type': 'pre_workout', 'dish_category': 'snack', 'serving_size_g': 140, 'calories': 220, 'protein_g': 6, 'carbs_g': 30, 'fats_g': 10, 'fiber_g': 5, 'prep_time_minutes': 2, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': ['tree_nuts'], 'popularity_score': 89, 'ingredients': [{'name': 'apple', 'quantity': 1, 'unit': 'piece'}, {'name': 'almond_butter', 'quantity': 20, 'unit': 'g'}]},
    {'name': 'Rice Cakes with Honey', 'name_hindi': 'राइस केक', 'description': 'Light carbs for energy', 'cuisine_type': 'continental', 'meal_type': 'pre_workout', 'dish_category': 'snack', 'serving_size_g': 60, 'calories': 150, 'protein_g': 3, 'carbs_g': 32, 'fats_g': 1, 'fiber_g': 1, 'prep_time_minutes': 2, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': [], 'popularity_score': 84, 'ingredients': [{'name': 'rice_cakes', 'quantity': 2, 'unit': 'piece'}, {'name': 'honey', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Dates and Nuts', 'name_hindi': 'खजूर', 'description': 'Natural energy boost', 'cuisine_type': 'continental', 'meal_type': 'pre_workout', 'dish_category': 'snack', 'serving_size_g': 80, 'calories': 210, 'protein_g': 5, 'carbs_g': 36, 'fats_g': 7, 'fiber_g': 4, 'prep_time_minutes': 0, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': ['tree_nuts'], 'popularity_score': 88, 'ingredients': [{'name': 'dates', 'quantity': 50, 'unit': 'g'}, {'name': 'almonds', 'quantity': 20, 'unit': 'g'}, {'name': 'walnuts', 'quantity': 10, 'unit': 'g'}]},
    {'name': 'Smoothie with Oats', 'name_hindi': 'ओट्स स्मूदी', 'description': 'Liquid energy drink', 'cuisine_type': 'continental', 'meal_type': 'pre_workout', 'dish_category': 'beverage', 'serving_size_g': 300, 'calories': 280, 'protein_g': 10, 'carbs_g': 48, 'fats_g': 6, 'fiber_g': 5, 'prep_time_minutes': 5, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 90, 'ingredients': [{'name': 'banana', 'quantity': 1, 'unit': 'piece'}, {'name': 'rolled_oats', 'quantity': 30, 'unit': 'g'}, {'name': 'milk', 'quantity': 200, 'unit': 'ml'}, {'name': 'honey', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Toast with Jam', 'name_hindi': 'टोस्ट जैम', 'description': 'Simple carb source', 'cuisine_type': 'continental', 'meal_type': 'pre_workout', 'dish_category': 'snack', 'serving_size_g': 80, 'calories': 180, 'protein_g': 5, 'carbs_g': 35, 'fats_g': 2, 'fiber_g': 3, 'prep_time_minutes': 3, 'cook_time_minutes': 2, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['wheat'], 'popularity_score': 85, 'ingredients': [{'name': 'whole_wheat_bread', 'quantity': 2, 'unit': 'slice'}, {'name': 'fruit_jam', 'quantity': 20, 'unit': 'g'}]},
    {'name': 'Energy Bites', 'name_hindi': 'एनर्जी बाइट्स', 'description': 'Quick energy snack', 'cuisine_type': 'continental', 'meal_type': 'pre_workout', 'dish_category': 'snack', 'serving_size_g': 70, 'calories': 190, 'protein_g': 6, 'carbs_g': 30, 'fats_g': 6, 'fiber_g': 4, 'prep_time_minutes': 10, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': True, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': False, 'contains_allergens': ['tree_nuts'], 'popularity_score': 86, 'ingredients': [{'name': 'dates', 'quantity': 40, 'unit': 'g'}, {'name': 'almonds', 'quantity': 15, 'unit': 'g'}, {'name': 'rolled_oats', 'quantity': 20, 'unit': 'g'}]},
    {'name': 'Fruit Smoothie', 'name_hindi': 'फ्रूट स्मूदी', 'description': 'Quick liquid energy', 'cuisine_type': 'continental', 'meal_type': 'pre_workout', 'dish_category': 'beverage', 'serving_size_g': 300, 'calories': 240, 'protein_g': 8, 'carbs_g': 48, 'fats_g': 4, 'fiber_g': 4, 'prep_time_minutes': 5, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 89, 'ingredients': [{'name': 'banana', 'quantity': 1, 'unit': 'piece'}, {'name': 'mango', 'quantity': 80, 'unit': 'g'}, {'name': 'milk', 'quantity': 200, 'unit': 'ml'}, {'name': 'honey', 'quantity': 10, 'unit': 'ml'}]},
]

# Post-Workout Dishes (10+ dishes)
POST_WORKOUT_DISHES = [
    {
        'name': 'Whey Protein Shake',
        'name_hindi': 'प्रोटीन शेक',
        'description': 'Fast-absorbing protein shake',
        'cuisine_type': 'continental',
        'meal_type': 'post_workout',
        'dish_category': 'beverage',
        'serving_size_g': 300,
        'calories': 280,
        'protein_g': 35,
        'carbs_g': 25,
        'fats_g': 4,
        'fiber_g': 2,
        'prep_time_minutes': 3,
        'cook_time_minutes': 0,
        'difficulty_level': 'easy',
        'is_vegetarian': True,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': False,
        'is_nut_free': True,
        'contains_allergens': ['dairy'],
        'popularity_score': 95,
        'ingredients': [
            {'name': 'whey_protein', 'quantity': 30, 'unit': 'g'},
            {'name': 'milk', 'quantity': 250, 'unit': 'ml'},
            {'name': 'banana', 'quantity': 1, 'unit': 'piece'},
        ]
    },
    {
        'name': 'Chicken and Sweet Potato',
        'name_hindi': 'चिकन शकरकंद',
        'description': 'Lean protein with complex carbs',
        'cuisine_type': 'continental',
        'meal_type': 'post_workout',
        'dish_category': 'main_course',
        'serving_size_g': 350,
        'calories': 420,
        'protein_g': 40,
        'carbs_g': 45,
        'fats_g': 8,
        'fiber_g': 6,
        'prep_time_minutes': 10,
        'cook_time_minutes': 25,
        'difficulty_level': 'easy',
        'is_vegetarian': False,
        'is_vegan': False,
        'is_gluten_free': True,
        'is_dairy_free': True,
        'is_nut_free': True,
        'contains_allergens': [],
        'popularity_score': 93,
        'ingredients': [
            {'name': 'chicken_breast', 'quantity': 200, 'unit': 'g'},
            {'name': 'sweet_potato', 'quantity': 150, 'unit': 'g'},
            {'name': 'olive_oil', 'quantity': 8, 'unit': 'ml'},
            {'name': 'salt', 'quantity': 2, 'unit': 'g'},
            {'name': 'black_pepper', 'quantity': 1, 'unit': 'g'},
        ]
    },
    # Additional 8+ post-workout dishes to reach 10+ total
    {'name': 'Tuna Sandwich', 'name_hindi': 'टूना सैंडविच', 'description': 'High protein sandwich', 'cuisine_type': 'continental', 'meal_type': 'post_workout', 'dish_category': 'main_course', 'serving_size_g': 280, 'calories': 380, 'protein_g': 32, 'carbs_g': 42, 'fats_g': 10, 'fiber_g': 5, 'prep_time_minutes': 10, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['fish', 'wheat'], 'popularity_score': 88, 'ingredients': [{'name': 'tuna', 'quantity': 120, 'unit': 'g'}, {'name': 'whole_wheat_bread', 'quantity': 4, 'unit': 'slice'}, {'name': 'lettuce', 'quantity': 30, 'unit': 'g'}, {'name': 'tomato', 'quantity': 40, 'unit': 'g'}]},
    {'name': 'Egg White Omelette with Toast', 'name_hindi': 'एग व्हाइट ऑमलेट', 'description': 'Pure protein meal', 'cuisine_type': 'continental', 'meal_type': 'post_workout', 'dish_category': 'main_course', 'serving_size_g': 280, 'calories': 300, 'protein_g': 30, 'carbs_g': 32, 'fats_g': 6, 'fiber_g': 4, 'prep_time_minutes': 5, 'cook_time_minutes': 10, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': False, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['eggs', 'wheat'], 'popularity_score': 91, 'ingredients': [{'name': 'egg_whites', 'quantity': 6, 'unit': 'piece'}, {'name': 'whole_wheat_bread', 'quantity': 2, 'unit': 'slice'}, {'name': 'spinach', 'quantity': 40, 'unit': 'g'}, {'name': 'olive_oil', 'quantity': 5, 'unit': 'ml'}]},
    {'name': 'Greek Yogurt Parfait', 'name_hindi': 'ग्रीक दही परफेट', 'description': 'Protein-rich yogurt bowl', 'cuisine_type': 'continental', 'meal_type': 'post_workout', 'dish_category': 'beverage', 'serving_size_g': 320, 'calories': 340, 'protein_g': 28, 'carbs_g': 48, 'fats_g': 6, 'fiber_g': 5, 'prep_time_minutes': 5, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 89, 'ingredients': [{'name': 'greek_yogurt', 'quantity': 250, 'unit': 'g'}, {'name': 'banana', 'quantity': 1, 'unit': 'piece'}, {'name': 'granola', 'quantity': 30, 'unit': 'g'}, {'name': 'honey', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Paneer Bhurji with Roti', 'name_hindi': 'पनीर भुर्जी', 'description': 'Scrambled cottage cheese', 'cuisine_type': 'north_indian', 'meal_type': 'post_workout', 'dish_category': 'main_course', 'serving_size_g': 350, 'calories': 420, 'protein_g': 28, 'carbs_g': 42, 'fats_g': 16, 'fiber_g': 5, 'prep_time_minutes': 10, 'cook_time_minutes': 15, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': False, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['wheat', 'dairy'], 'popularity_score': 90, 'ingredients': [{'name': 'paneer', 'quantity': 150, 'unit': 'g'}, {'name': 'whole_wheat_flour', 'quantity': 80, 'unit': 'g'}, {'name': 'onion', 'quantity': 40, 'unit': 'g'}, {'name': 'tomato', 'quantity': 40, 'unit': 'g'}, {'name': 'oil', 'quantity': 12, 'unit': 'ml'}]},
    {'name': 'Chocolate Milk', 'name_hindi': 'चॉकलेट मिल्क', 'description': 'Recovery drink', 'cuisine_type': 'continental', 'meal_type': 'post_workout', 'dish_category': 'beverage', 'serving_size_g': 300, 'calories': 260, 'protein_g': 16, 'carbs_g': 40, 'fats_g': 6, 'fiber_g': 1, 'prep_time_minutes': 2, 'cook_time_minutes': 0, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['dairy'], 'popularity_score': 92, 'ingredients': [{'name': 'milk', 'quantity': 300, 'unit': 'ml'}, {'name': 'cocoa_powder', 'quantity': 15, 'unit': 'g'}, {'name': 'honey', 'quantity': 15, 'unit': 'ml'}]},
    {'name': 'Grilled Fish with Rice', 'name_hindi': 'ग्रिल्ड मछली', 'description': 'Lean protein with carbs', 'cuisine_type': 'continental', 'meal_type': 'post_workout', 'dish_category': 'main_course', 'serving_size_g': 400, 'calories': 450, 'protein_g': 38, 'carbs_g': 52, 'fats_g': 10, 'fiber_g': 3, 'prep_time_minutes': 10, 'cook_time_minutes': 20, 'difficulty_level': 'easy', 'is_vegetarian': False, 'is_vegan': False, 'is_gluten_free': True, 'is_dairy_free': True, 'is_nut_free': True, 'contains_allergens': ['fish'], 'popularity_score': 89, 'ingredients': [{'name': 'fish', 'quantity': 200, 'unit': 'g'}, {'name': 'basmati_rice', 'quantity': 100, 'unit': 'g'}, {'name': 'lemon_juice', 'quantity': 15, 'unit': 'ml'}, {'name': 'olive_oil', 'quantity': 10, 'unit': 'ml'}]},
    {'name': 'Protein Pancakes', 'name_hindi': 'प्रोटीन पैनकेक', 'description': 'High protein recovery meal', 'cuisine_type': 'continental', 'meal_type': 'post_workout', 'dish_category': 'main_course', 'serving_size_g': 280, 'calories': 380, 'protein_g': 32, 'carbs_g': 45, 'fats_g': 10, 'fiber_g': 4, 'prep_time_minutes': 10, 'cook_time_minutes': 15, 'difficulty_level': 'easy', 'is_vegetarian': True, 'is_vegan': False, 'is_gluten_free': False, 'is_dairy_free': False, 'is_nut_free': True, 'contains_allergens': ['wheat', 'dairy', 'eggs'], 'popularity_score': 90, 'ingredients': [{'name': 'protein_powder', 'quantity': 30, 'unit': 'g'}, {'name': 'whole_wheat_flour', 'quantity': 60, 'unit': 'g'}, {'name': 'eggs', 'quantity': 2, 'unit': 'piece'}, {'name': 'milk', 'quantity': 100, 'unit': 'ml'}, {'name': 'honey', 'quantity': 15, 'unit': 'ml'}]},
]

# Combine all dishes
ALL_DISHES = (
    BREAKFAST_DISHES +
    LUNCH_DISHES +
    DINNER_DISHES +
    SNACK_DISHES +
    PRE_WORKOUT_DISHES +
    POST_WORKOUT_DISHES
)
